import type { CodegenFile } from "@ucdjs/codegen";
import type { ProcessedFieldsFile } from "@ucdjs/codegen/fields";
import type { CLIArguments } from "../../cli-utils";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { trimLeadingSlash } from "@luxass/utils";
import { flattenFilePaths } from "@ucdjs-internal/shared";
import { createUCDClient } from "@ucdjs/client";
import { runFieldsCodegen } from "@ucdjs/codegen/fields";
import { UCDJS_API_BASE_URL } from "@ucdjs/env";
import { printHelp } from "../../cli-utils";
import { CLIError } from "../../errors";
import { output } from "../../output";

export interface CLICodegenFieldsCmdOptions {
  flags: CLIArguments<{
    openaiKey?: string;
    outputDir?: string;
    bundle?: boolean | string;
    storeDir?: string;
    baseUrl?: string;
  }>;
  versions: string[];
}

function flattenVersion(version: string): string {
  const parts = version.split(".");
  while (parts.length > 1 && parts.at(-1) === "0") {
    parts.pop();
  }
  return parts.join(".");
}

const VERSION_DIR_RE = /^\d+\.\d+\.\d+$/;

async function collectRemoteFiles(
  versions: string[],
  baseUrl: string,
): Promise<CodegenFile[]> {
  const client = await createUCDClient(baseUrl);

  let resolvedVersions = versions;
  if (resolvedVersions.length === 0) {
    const { data, error } = await client.versions.list();
    if (error || !data) {
      throw new CLIError("Failed to fetch available Unicode versions from the API.", {
        details: [error?.message ?? "No data returned."],
      });
    }
    resolvedVersions = data.map((v) => v.version);
  }

  output.info(`Processing ${resolvedVersions.length} version(s): ${resolvedVersions.join(", ")}`);

  const files: CodegenFile[] = [];

  for (const version of resolvedVersions) {
    const { data: tree, error: treeError } = await client.versions.getFileTree(version);
    if (treeError || !tree) {
      output.warning(`Could not get file tree for version ${version}, skipping.`);
      continue;
    }

    const paths = flattenFilePaths(tree);
    const txtPaths = paths.filter((p) => p.endsWith(".txt") && !p.endsWith("Test.txt"));

    output.info(`Found ${txtPaths.length} file(s) for version ${version}.`);

    for (const treePath of txtPaths) {
      const cleanPath = trimLeadingSlash(treePath);
      const { data: content, error: fileError } = await client.files.get(cleanPath);

      if (fileError || content == null || typeof content !== "string") {
        output.warning(`Could not fetch ${cleanPath}, skipping.`);
        continue;
      }

      files.push({
        content,
        fileName: path.basename(cleanPath, ".txt"),
        version: flattenVersion(version),
      });
    }
  }

  return files;
}

async function collectLocalFiles(
  storeDir: string,
  versions: string[],
): Promise<CodegenFile[]> {
  const resolvedStoreDir = path.resolve(storeDir);

  let resolvedVersions = versions;
  if (resolvedVersions.length === 0) {
    const entries = await readdir(resolvedStoreDir, { withFileTypes: true });
    resolvedVersions = entries
      .filter((e) => e.isDirectory() && VERSION_DIR_RE.test(e.name))
      .map((e) => e.name);

    if (resolvedVersions.length === 0) {
      throw new CLIError(`No version directories found in ${storeDir}.`, {
        details: ["Expected directories named like 16.0.0, 15.0.0, etc."],
      });
    }
  }

  output.info(`Processing ${resolvedVersions.length} version(s): ${resolvedVersions.join(", ")}`);

  const files: CodegenFile[] = [];

  for (const version of resolvedVersions) {
    const versionDir = path.join(resolvedStoreDir, version);
    let entries;

    try {
      entries = await readdir(versionDir, { withFileTypes: true, recursive: true });
    } catch {
      output.warning(`Could not read directory ${versionDir}, skipping version ${version}.`);
      continue;
    }

    const txtEntries = entries.filter(
      (e) => e.isFile() && e.name.endsWith(".txt") && !e.name.endsWith("Test.txt"),
    );

    output.info(`Found ${txtEntries.length} file(s) for version ${version}.`);

    for (const entry of txtEntries) {
      const filePath = path.join(entry.parentPath, entry.name);
      const content = await readFile(filePath, "utf-8");
      files.push({
        content,
        fileName: path.basename(entry.name, ".txt"),
        version: flattenVersion(version),
      });
    }
  }

  return files;
}

async function writeBundledFile(
  version: string,
  results: ProcessedFieldsFile[],
  bundleTemplate: string,
  outputDir: string | undefined,
): Promise<void> {
  let bundledCode = `// This file is generated by ucd codegen. Do not edit this file directly.\n`;
  bundledCode += `// Unicode Version: ${version}\n\n`;

  for (const result of results) {
    bundledCode += `\n// #region ${result.fileName}\n`;
    bundledCode += result.code;
    bundledCode += `\n// #endregion\n`;
  }

  const bundleFileName = bundleTemplate.replace("{version}", version);
  let bundlePath;
  if (path.isAbsolute(bundleFileName) || bundleFileName.startsWith("./") || bundleFileName.startsWith("../")) {
    bundlePath = path.resolve(bundleFileName);
  } else if (outputDir) {
    bundlePath = path.resolve(path.join(outputDir, bundleFileName));
  } else {
    bundlePath = path.resolve(bundleFileName);
  }

  if (!bundlePath.endsWith(".ts")) {
    bundlePath += ".ts";
  }

  await mkdir(path.dirname(bundlePath), { recursive: true });
  await writeFile(bundlePath, bundledCode, "utf-8");
  output.success(`Generated bundled fields for Unicode ${version} in ${bundlePath}`);
}

export async function runFieldCodegen({ versions, flags }: CLICodegenFieldsCmdOptions) {
  if (flags?.help || flags?.h) {
    printHelp({
      headline: "Generate TypeScript field definitions from Unicode data files",
      commandName: "ucd codegen fields",
      usage: "[versions...] [...flags]",
      tables: {
        Flags: [
          ["--openai-key (-k)", "The OpenAI API key to use. (can also be set using OPENAI_API_KEY env var)"],
          ["--store-dir", "Read files from a local UCD store directory instead of the remote API."],
          ["--base-url", "Base URL for the remote UCD API. (default: api.ucdjs.dev)"],
          ["--output-dir", "Output directory for generated files. (default: .codegen)"],
          ["--bundle <filename>", "Combine generated files into a single file per version. Use {version} for version-specific naming."],
          ["--help (-h)", "See all available flags."],
        ],
      },
    });
    return;
  }

  const openaiKey = flags.openaiKey || process.env.OPENAI_API_KEY;
  if (!openaiKey) {
    throw new CLIError("No OpenAI API key provided.", {
      details: ["Please provide an OpenAI API key via --openai-key flag or OPENAI_API_KEY environment variable."],
    });
  }

  const files = flags.storeDir
    ? await collectLocalFiles(flags.storeDir, versions)
    : await collectRemoteFiles(versions, flags.baseUrl ?? UCDJS_API_BASE_URL);

  if (files.length === 0) {
    output.warning("No files found to process.");
    return;
  }

  output.info(`Found ${files.length} files to process.`);

  const results = await runFieldsCodegen({ files, openaiKey });

  const shouldBundle = typeof flags.bundle === "string" || flags.bundle === true;
  const bundleTemplate = typeof flags.bundle === "string" ? flags.bundle : "index.ts";

  let outputDir = flags.outputDir;
  if (!outputDir) {
    if (shouldBundle && (path.isAbsolute(bundleTemplate) || bundleTemplate.startsWith("./") || bundleTemplate.startsWith("../"))) {
      outputDir = path.dirname(bundleTemplate);
    } else {
      outputDir = path.join(process.cwd(), ".codegen");
    }
  }

  await mkdir(outputDir, { recursive: true });

  if (!shouldBundle) {
    await Promise.all(results.map((result: ProcessedFieldsFile) =>
      writeFile(path.join(outputDir, `${result.fileName}.ts`), result.code, "utf-8"),
    ));
    output.success(`Generated fields for ${results.length} files in ${outputDir}`);
    return;
  }

  const resultsByVersion = new Map<string, ProcessedFieldsFile[]>();
  for (const result of results) {
    const versionResults = resultsByVersion.get(result.version) ?? [];
    versionResults.push(result);
    resultsByVersion.set(result.version, versionResults);
  }

  await Promise.all(
    Array.from(resultsByVersion.entries(), ([version, versionResults]) =>
      writeBundledFile(version, versionResults, bundleTemplate, outputDir)),
  );
}
