import { useInspectData } from "#hooks/use-inspect-data";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { ArrowRight, ChevronDown, ChevronRight, FileOutput, FolderOutput, RouteIcon } from "lucide-react";
import { useMemo, useState } from "react";

export const Route = createFileRoute("/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs")({
  component: RouteComponent,
});

function RouteComponent() {
  const params = Route.useParams();
  const navigate = Route.useNavigate();
  const { pipeline, search } = useInspectData();

  const outputs = useMemo(() => {
    return pipeline.routes.flatMap((route) => {
      return route.outputs.map((output, index) => ({
        key: `${route.id}:${index}`,
        routeId: route.id,
        outputIndex: index,
        dir: output.dir ?? "Default route output directory",
        fileName: output.fileName ?? "Generated by route configuration",
      }));
    });
  }, [pipeline.routes]);

  const outputsByRoute = useMemo(() => {
    const grouped = new Map<string, typeof outputs>();
    for (const output of outputs) {
      const list = grouped.get(output.routeId);
      if (list) {
        list.push(output);
      } else {
        grouped.set(output.routeId, [output]);
      }
    }
    return grouped;
  }, [outputs]);

  const selectedOutput = outputs.find((output) => output.key === search.output)
    ?? outputs.find((output) => output.routeId === search.route)
    ?? outputs[0]
    ?? null;

  const [expandedRoutes, setExpandedRoutes] = useState<Set<string>>(() => {
    return new Set(selectedOutput ? [selectedOutput.routeId] : []);
  });

  function toggleRoute(routeId: string) {
    setExpandedRoutes((prev) => {
      const next = new Set(prev);
      if (next.has(routeId)) {
        next.delete(routeId);
      } else {
        next.add(routeId);
      }
      return next;
    });
  }

  return (
    <Card>
      {selectedOutput
        ? (
            <>
              <CardHeader className="border-b border-border/60 pb-4">
                <div className="flex items-center gap-2.5">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted/40">
                    <FolderOutput className="h-4.5 w-4.5 text-muted-foreground" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <CardTitle className="truncate text-lg">
                        {selectedOutput.routeId}
                        {" "}
                        <span className="text-muted-foreground">
                          output
                          {selectedOutput.outputIndex + 1}
                        </span>
                      </CardTitle>
                    </div>
                    <CardDescription className="mt-0.5">
                      Output definition for where this route writes artifacts.
                    </CardDescription>
                  </div>
                </div>
                <div className="mt-3 grid grid-cols-2 gap-3">
                  <div className="rounded-lg border border-border/60 bg-muted/20 px-3 py-2">
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <FolderOutput className="h-3.5 w-3.5" />
                      Total outputs
                    </div>
                    <div className="mt-1 text-xl font-semibold tabular-nums">{outputs.length}</div>
                  </div>
                  <div className="rounded-lg border border-border/60 bg-muted/20 px-3 py-2">
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <RouteIcon className="h-3.5 w-3.5" />
                      Routes with outputs
                    </div>
                    <div className="mt-1 text-xl font-semibold tabular-nums">{outputsByRoute.size}</div>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-6 pt-6">
                <section className="space-y-3">
                  <div className="flex items-center gap-2">
                    <FolderOutput className="h-4 w-4 text-muted-foreground" />
                    <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Pipeline outputs</h3>
                  </div>
                  <div className="rounded-lg border border-border/60">
                    {Array.from(outputsByRoute.entries(), ([routeId, routeOutputs], groupIndex) => {
                      const expanded = expandedRoutes.has(routeId);
                      return (
                        <div key={routeId} className={groupIndex > 0 ? "border-t border-border/60" : ""}>
                          <button
                            type="button"
                            onClick={() => toggleRoute(routeId)}
                            className="flex w-full items-center gap-2 px-3 py-2.5 text-left transition-colors hover:bg-muted/30"
                          >
                            {expanded
                              ? <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                              : <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />}
                            <RouteIcon className="h-3.5 w-3.5 text-muted-foreground" />
                            <span className="text-sm font-medium">{routeId}</span>
                            <span className="ml-auto text-xs text-muted-foreground">
                              {routeOutputs.length}
                              {" "}
                              {routeOutputs.length === 1 ? "output" : "outputs"}
                            </span>
                          </button>
                          {expanded && (
                            <div className="border-t border-border/40 bg-muted/5">
                              {routeOutputs.map((output) => {
                                const active = output.key === selectedOutput.key;
                                return (
                                  <button
                                    key={output.key}
                                    type="button"
                                    onClick={() => {
                                      navigate({
                                        search: (current) => ({
                                          q: current.q,
                                          route: output.routeId,
                                          transform: undefined,
                                          output: output.key,
                                        }),
                                      });
                                    }}
                                    className={`flex w-full items-center gap-2 py-2 pl-10 pr-3 text-left transition-colors ${active ? "bg-primary/5" : "hover:bg-muted/20"}`}
                                  >
                                    <FileOutput className={`h-3.5 w-3.5 ${active ? "text-primary" : "text-muted-foreground"}`} />
                                    <span className="text-xs font-medium">
                                      Output
                                      {" "}
                                      {output.outputIndex + 1}
                                    </span>
                                    <span className="ml-auto truncate text-[11px] text-muted-foreground">
                                      {output.fileName}
                                    </span>
                                  </button>
                                );
                              })}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </section>

                <section className="space-y-3">
                  <div className="flex items-center gap-2">
                    <FileOutput className="h-4 w-4 text-muted-foreground" />
                    <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Output details</h3>
                  </div>
                  <div className="grid gap-3 md:grid-cols-2">
                    <div className="rounded-lg border border-border/60 p-3">
                      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Directory</div>
                      <code className="mt-1.5 block text-xs">
                        {selectedOutput.dir}
                      </code>
                    </div>
                    <div className="rounded-lg border border-border/60 p-3">
                      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">File name</div>
                      <code className="mt-1.5 block text-xs">
                        {selectedOutput.fileName}
                      </code>
                    </div>
                  </div>
                </section>

                <section className="space-y-3">
                  <div className="flex items-center gap-2">
                    <RouteIcon className="h-4 w-4 text-muted-foreground" />
                    <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Owning route</h3>
                  </div>
                  <Link
                    to="/s/$sourceId/$sourceFileId/$pipelineId/inspect"
                    params={params}
                    search={(current) => ({
                      q: current.q,
                      route: selectedOutput.routeId,
                      transform: undefined,
                      output: undefined,
                    })}
                    className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-2 text-sm font-medium text-foreground transition-colors hover:bg-muted"
                  >
                    Open
                    {" "}
                    {selectedOutput.routeId}
                    <ArrowRight className="h-3.5 w-3.5" />
                  </Link>
                </section>
              </CardContent>
            </>
          )
        : (
            <CardHeader className="py-16 text-center">
              <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-muted/50">
                <FolderOutput className="h-6 w-6 text-muted-foreground/60" />
              </div>
              <CardTitle className="text-base">No outputs defined</CardTitle>
              <CardDescription>
                This pipeline has no output definitions configured.
              </CardDescription>
            </CardHeader>
          )}
    </Card>
  );
}
