import { createFileRoute, getRouteApi, Link } from "@tanstack/react-router";
import { Badge } from "@ucdjs-internal/shared-ui/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { useEffect, useMemo } from "react";

const PipelineRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId");
const InspectRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId/inspect");

export const Route = createFileRoute("/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs")({
  component: RouteComponent,
});

function RouteComponent() {
  const params = Route.useParams();
  const navigate = Route.useNavigate();
  const search = InspectRoute.useSearch();
  const { pipelineResponse } = PipelineRoute.useLoaderData();
  const pipeline = pipelineResponse.pipeline;

  const outputs = useMemo(() => {
    return pipeline.routes.flatMap((route) => {
      return route.outputs.map((output, index) => ({
        key: `${route.id}:${index}`,
        routeId: route.id,
        outputIndex: index,
        dir: output.dir ?? "Default route output directory",
        fileName: output.fileName ?? "Generated by route configuration",
      }));
    });
  }, [pipeline.routes]);

  const selectedOutput = outputs.find((output) => output.key === search.output)
    ?? outputs.find((output) => output.routeId === search.route)
    ?? outputs[0]
    ?? null;

  useEffect(() => {
    if (!selectedOutput || search.output === selectedOutput.key) {
      return;
    }

    navigate({
      replace: true,
      search: (current) => ({
        q: current.q,
        route: selectedOutput.routeId,
        transform: undefined,
        output: selectedOutput.key,
      }),
    });
  }, [navigate, search.output, selectedOutput]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>{selectedOutput ? `${selectedOutput.routeId} output ${selectedOutput.outputIndex + 1}` : "No output selected"}</CardTitle>
        <CardDescription>
          Output definitions describe where a route writes artifacts, not the runtime files it produced.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {selectedOutput
          ? (
              <>
                <section className="space-y-3">
                  <div>
                    <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Pipeline outputs</h3>
                    <p className="text-sm text-muted-foreground">
                      Select an output definition to inspect where a route writes generated artifacts.
                    </p>
                  </div>
                  <div className="grid gap-3 md:grid-cols-2">
                    {outputs.map((output) => (
                      <button
                        key={output.key}
                        type="button"
                        onClick={() => {
                          navigate({
                            search: (current) => ({
                              q: current.q,
                              route: output.routeId,
                              transform: undefined,
                              output: output.key,
                            }),
                          });
                        }}
                        className={`rounded-lg border p-4 text-left transition-colors ${output.key === selectedOutput.key ? "border-primary/40 bg-primary/5" : "border-border/60 bg-muted/10 hover:bg-muted/20"}`}
                      >
                        <div className="flex items-center justify-between gap-3">
                          <div className="text-sm font-medium">{output.routeId}</div>
                          <Badge variant="outline">
                            output
                            {" "}
                            {output.outputIndex + 1}
                          </Badge>
                        </div>
                        <div className="mt-3 grid gap-1 text-[11px] text-muted-foreground">
                          <span>{output.dir}</span>
                          <span>{output.fileName}</span>
                        </div>
                      </button>
                    ))}
                  </div>
                </section>

                <section className="grid gap-3 md:grid-cols-2">
                  <div className="rounded-lg border border-border/60 bg-muted/10 p-4">
                    <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Directory</div>
                    <div className="mt-2 rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
                      {selectedOutput.dir}
                    </div>
                  </div>
                  <div className="rounded-lg border border-border/60 bg-muted/10 p-4">
                    <div className="text-[11px] uppercase tracking-wide text-muted-foreground">File name</div>
                    <div className="mt-2 rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
                      {selectedOutput.fileName}
                    </div>
                  </div>
                </section>

                <section className="space-y-3">
                  <div>
                    <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Owning route</h3>
                    <p className="text-sm text-muted-foreground">
                      Return to the route inspector to see how this route depends on other parts of the pipeline.
                    </p>
                  </div>
                  <Link
                    to="/s/$sourceId/$sourceFileId/$pipelineId/inspect"
                    params={params}
                    search={(current) => ({
                      q: current.q,
                      route: selectedOutput.routeId,
                      transform: undefined,
                      output: undefined,
                    })}
                    className="inline-flex items-center rounded-md border border-border px-3 py-2 text-sm font-medium text-foreground transition-colors hover:bg-muted"
                  >
                    Open
                    {" "}
                    {selectedOutput.routeId}
                  </Link>
                </section>
              </>
            )
          : (
              <div className="text-sm text-muted-foreground">No output definitions exist for this pipeline.</div>
            )}
      </CardContent>
    </Card>
  );
}
