import type { PipelineDetails } from "#shared/schemas/pipeline";
import { createFileRoute, getRouteApi, Link, Outlet, useMatches, useNavigate } from "@tanstack/react-router";
import { Badge } from "@ucdjs-internal/shared-ui/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { Input } from "@ucdjs-internal/shared-ui/ui/input";
import { FolderOutput, Workflow as PipelineIcon, Shuffle, Spline } from "lucide-react";
import { useMemo, useState } from "react";

const PipelineRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId");

type TabId = "routes" | "transforms" | "outputs";

interface TransformEntry {
  name: string;
  routes: string[];
}

interface OutputEntry {
  key: string;
  routeId: string;
  outputIndex: number;
  dir: string;
  fileName: string;
}

export const Route = createFileRoute("/s/$sourceId/$sourceFileId/$pipelineId/inspect")({
  component: InspectLayout,
});

function useActiveTab(): TabId {
  const matches = useMatches();
  const ids = matches.map((m) => m.id);
  if (ids.some((id) => id.includes("/inspect/transforms"))) return "transforms";
  if (ids.some((id) => id.includes("/inspect/outputs"))) return "outputs";
  return "routes";
}

function InspectLayout() {
  const { pipelineResponse } = PipelineRoute.useLoaderData();
  const pipeline = pipelineResponse.pipeline;
  const { sourceId, sourceFileId, pipelineId } = Route.useParams();
  const activeTab = useActiveTab();

  return (
    <div className="p-4 sm:p-6">
      <div className="grid gap-6 xl:grid-cols-[22rem_minmax(0,1fr)]">
        <aside className="space-y-4 xl:sticky xl:top-6 xl:self-start">
          <InspectSidebar
            pipeline={pipeline}
            activeTab={activeTab}
            sourceId={sourceId}
            sourceFileId={sourceFileId}
            pipelineId={pipelineId}
          />
        </aside>
        <main className="min-w-0 space-y-4">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

interface InspectSidebarProps {
  pipeline: PipelineDetails;
  activeTab: TabId;
  sourceId: string;
  sourceFileId: string;
  pipelineId: string;
}

function InspectSidebar({
  pipeline,
  activeTab,
  sourceId,
  sourceFileId,
  pipelineId,
}: InspectSidebarProps) {
  const navigate = useNavigate();
  const [filterValue, setFilterValue] = useState("");
  const normalizedFilter = filterValue.trim().toLowerCase();

  const transformCount = useMemo(() => {
    return new Set(pipeline.routes.flatMap((route) => route.transforms)).size;
  }, [pipeline.routes]);

  const outputCount = useMemo(() => {
    return pipeline.routes.reduce((count, route) => count + route.outputs.length, 0);
  }, [pipeline.routes]);

  const transforms = useMemo<TransformEntry[]>(() => {
    const transformMap = new Map<string, string[]>();
    for (const route of pipeline.routes) {
      for (const transform of route.transforms) {
        const routes = transformMap.get(transform);
        if (routes) {
          routes.push(route.id);
        } else {
          transformMap.set(transform, [route.id]);
        }
      }
    }
    return Array.from(transformMap.entries(), ([name, routes]) => ({ name, routes }))
      .sort((left, right) => left.name.localeCompare(right.name));
  }, [pipeline.routes]);

  const outputs = useMemo<OutputEntry[]>(() => {
    return pipeline.routes.flatMap((route) =>
      route.outputs.map((output, index) => ({
        key: `${route.id}:${index}`,
        routeId: route.id,
        outputIndex: index,
        dir: output.dir ?? "Default route output directory",
        fileName: output.fileName ?? "Generated by route configuration",
      })),
    );
  }, [pipeline.routes]);

  const filteredRoutes = useMemo(() => {
    if (!normalizedFilter) return pipeline.routes;
    return pipeline.routes.filter((route) => {
      if (route.id.toLowerCase().includes(normalizedFilter)) return true;
      if (route.transforms.some((t) => t.toLowerCase().includes(normalizedFilter))) return true;
      if (route.outputs.some((o) =>
        (o.dir ?? "").toLowerCase().includes(normalizedFilter)
        || (o.fileName ?? "").toLowerCase().includes(normalizedFilter),
      )) return true;
      return route.emits.some((e) => e.id.toLowerCase().includes(normalizedFilter))
        || route.depends.some((d) =>
          d.type === "route"
            ? d.routeId.toLowerCase().includes(normalizedFilter)
            : `${d.routeId}:${d.artifactName}`.toLowerCase().includes(normalizedFilter),
        );
    });
  }, [pipeline.routes, normalizedFilter]);

  const filteredTransforms = useMemo(() => {
    if (!normalizedFilter) return transforms;
    return transforms.filter((t) => t.name.toLowerCase().includes(normalizedFilter));
  }, [transforms, normalizedFilter]);

  const filteredOutputs = useMemo(() => {
    if (!normalizedFilter) return outputs;
    return outputs.filter((o) =>
      o.dir.toLowerCase().includes(normalizedFilter)
      || o.fileName.toLowerCase().includes(normalizedFilter)
      || o.routeId.toLowerCase().includes(normalizedFilter),
    );
  }, [outputs, normalizedFilter]);

  const tabs: { id: TabId; label: string; count: number; to: string }[] = [
    { id: "routes", label: "Routes", count: pipeline.routes.length, to: "/s/$sourceId/$sourceFileId/$pipelineId/inspect/routes" },
    { id: "transforms", label: "Transforms", count: transformCount, to: "/s/$sourceId/$sourceFileId/$pipelineId/inspect/transforms" },
    { id: "outputs", label: "Outputs", count: outputCount, to: "/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs" },
  ];

  function handleTabChange(tab: TabId) {
    setFilterValue("");
    const target = tabs.find((t) => t.id === tab);
    if (target) {
      navigate({
        to: target.to,
        params: { sourceId, sourceFileId, pipelineId },
      });
    }
  }

  return (
    <Card>
      <CardHeader className="border-b border-border/60 pb-4">
        <div className="flex items-start gap-3">
          <div className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-muted/10">
            <PipelineIcon className="h-4 w-4 text-muted-foreground" />
          </div>
          <div className="space-y-1">
            <div className="text-[11px] font-medium uppercase tracking-[0.16em] text-muted-foreground">Inspect</div>
            <CardTitle className="text-base">Pipeline</CardTitle>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 pt-5">
        <div className="flex flex-wrap gap-4 text-xs text-muted-foreground">
          <span className="inline-flex items-center gap-1.5">
            <Spline className="h-3.5 w-3.5" />
            <span className="font-medium tabular-nums text-foreground">{pipeline.routes.length}</span>
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Shuffle className="h-3.5 w-3.5" />
            <span className="font-medium tabular-nums text-foreground">{transformCount}</span>
          </span>
          <span className="inline-flex items-center gap-1.5">
            <FolderOutput className="h-3.5 w-3.5" />
            <span className="font-medium tabular-nums text-foreground">{outputCount}</span>
          </span>
        </div>

        <div className="flex border-b border-border/60">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              type="button"
              onClick={() => handleTabChange(tab.id)}
              className={`px-4 pb-2 text-xs font-medium transition-colors ${
                activeTab === tab.id
                  ? "border-b-2 border-foreground text-foreground"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {tab.label}
              {" "}
              <span className="tabular-nums text-muted-foreground">
                (
                {tab.count}
                )
              </span>
            </button>
          ))}
        </div>

        <Input
          value={filterValue}
          onChange={(event) => setFilterValue(event.target.value)}
          placeholder={
            activeTab === "routes"
              ? `Search ${pipeline.routes.length} routes\u2026`
              : activeTab === "transforms"
                ? `Search ${transformCount} transforms\u2026`
                : `Search ${outputCount} outputs\u2026`
          }
          aria-label="Search inspect items"
        />

        <div className="rounded-xl border border-border/60">
          {activeTab === "routes" && (
            filteredRoutes.length === 0
              ? (
                  <div className="px-4 py-10 text-sm text-muted-foreground">
                    No routes match the current filter.
                  </div>
                )
              : (
                  <div className="divide-y divide-border/60">
                    {filteredRoutes.map((route) => (
                      <Link
                        key={route.id}
                        to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/routes/$routeId"
                        params={{ sourceId, sourceFileId, pipelineId, routeId: route.id }}
                        className="relative flex w-full flex-col gap-2 px-4 py-3 text-left transition-colors hover:bg-muted/10 [&.active]:bg-muted/10 [&.active]:before:absolute [&.active]:before:inset-y-2 [&.active]:before:left-0 [&.active]:before:w-0.5 [&.active]:before:rounded-full [&.active]:before:bg-foreground/80"
                      >
                        <div className="flex items-center justify-between gap-3">
                          <div className="min-w-0">
                            <div className="truncate text-sm font-medium text-foreground">{route.id}</div>
                          </div>
                          {route.cache && <Badge variant="secondary" className="text-[10px]">Cacheable</Badge>}
                        </div>
                        <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-muted-foreground">
                          <span>
                            <span className="font-medium tabular-nums text-foreground/70">{route.depends.length}</span>
                            {" "}
                            depends
                          </span>
                          <span>
                            <span className="font-medium tabular-nums text-foreground/70">{route.transforms.length}</span>
                            {" "}
                            transforms
                          </span>
                          <span>
                            <span className="font-medium tabular-nums text-foreground/70">{route.outputs.length}</span>
                            {" "}
                            outputs
                          </span>
                        </div>
                      </Link>
                    ))}
                  </div>
                )
          )}

          {activeTab === "transforms" && (
            filteredTransforms.length === 0
              ? (
                  <div className="px-4 py-10 text-sm text-muted-foreground">
                    No transforms match the current filter.
                  </div>
                )
              : (
                  <div className="divide-y divide-border/60">
                    {filteredTransforms.map((transform) => (
                      <Link
                        key={transform.name}
                        to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/transforms/$name"
                        params={{ sourceId, sourceFileId, pipelineId, name: transform.name }}
                        className="relative flex w-full items-center justify-between gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/10 [&.active]:bg-muted/10 [&.active]:before:absolute [&.active]:before:inset-y-2 [&.active]:before:left-0 [&.active]:before:w-0.5 [&.active]:before:rounded-full [&.active]:before:bg-foreground/80"
                      >
                        <div className="flex min-w-0 items-center gap-2">
                          <Shuffle className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                          <div className="truncate text-sm font-medium text-foreground">{transform.name}</div>
                        </div>
                        <Badge variant="secondary" className="shrink-0 text-[10px]">
                          {transform.routes.length}
                          {" "}
                          {transform.routes.length === 1 ? "route" : "routes"}
                        </Badge>
                      </Link>
                    ))}
                  </div>
                )
          )}

          {activeTab === "outputs" && (
            filteredOutputs.length === 0
              ? (
                  <div className="px-4 py-10 text-sm text-muted-foreground">
                    No outputs match the current filter.
                  </div>
                )
              : (
                  <div className="divide-y divide-border/60">
                    {filteredOutputs.map((output) => (
                      <Link
                        key={output.key}
                        to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs/$outputKey"
                        params={{ sourceId, sourceFileId, pipelineId, outputKey: output.key }}
                        className="relative flex w-full flex-col gap-1 px-4 py-3 text-left transition-colors hover:bg-muted/10 [&.active]:bg-muted/10 [&.active]:before:absolute [&.active]:before:inset-y-2 [&.active]:before:left-0 [&.active]:before:w-0.5 [&.active]:before:rounded-full [&.active]:before:bg-foreground/80"
                      >
                        <div className="flex items-center gap-2">
                          <span className="text-[11px] text-muted-foreground">{output.routeId}</span>
                          <span className="truncate text-sm font-semibold text-foreground">
                            output
                            {output.outputIndex + 1}
                          </span>
                        </div>
                        <div className="truncate text-[11px] text-muted-foreground">{output.dir}</div>
                        <div className="truncate text-[11px] text-muted-foreground">{output.fileName}</div>
                      </Link>
                    ))}
                  </div>
                )
          )}
        </div>
      </CardContent>
    </Card>
  );
}
