packages:
  - packages/*

catalogs:
  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.4
    turbo: ^2.5.3
    msw: ^2.8.4
    "@vitest/coverage-v8": ^3.1.4
    "@vitest/ui": ^3.1.4
    "@ark/attest": ^0.46.0
    tsx: ^4.19.4

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils": ^0.9.0
    "@luxass/unicode-utils-new": npm:@luxass/unicode-utils@0.12.0-beta.5
    "@luxass/utils": ^2.3.0
    farver: ^0.4.2
    fs-extra: ^11.3.0
    yargs-parser: ^21.1.1
    defu: ^6.1.4
    arktype: ^2.1.20
    zod: ^3.25.42
    "@ai-sdk/openai": ^1.3.22
    ai: ^4.3.16
    p-limit: ^6.2.0
    knitwork: ^1.2.0
    picomatch: ^4.0.2

  dev:
    "@luxass/eslint-config": ^4.18.1
    "@types/fs-extra": ^11.0.4
    "@types/micromatch": ^4.0.9
    "@types/picomatch": ^4.0.0
    "@types/node": ^22.10.0
    "@types/yargs-parser": ^21.0.3
    eslint: ^9.27.0
    tsdown: ^0.12.5
    typescript: ^5.8.3
    vitest: ^3.1.4
    vitest-testdirs: ^4.0.0
    tsx: ^4.19.4
    publint: ^0.3.12

onlyBuiltDependencies:
  - esbuild
  - rolldown
