preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - "@luxass/unicode-utils"
  - "@luxass/msw-utils"

packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
  - "vscode"

catalogs:
  monorepo:
    "@changesets/changelog-github": 0.5.1
    "@changesets/cli": 2.29.7
    turbo: 2.5.8

  testing:
    "@vitest/coverage-istanbul": 3.2.4
    "@vitest/ui": 3.2.4
    vitest: 3.2.4
    vitest-testdirs: 4.2.1
    msw: 2.11.3
    "@cloudflare/vitest-pool-workers": 0.9.3
    "@luxass/msw-utils": 0.1.1

  linting:
    "@luxass/eslint-config": 5.3.2
    "@stoplight/spectral-cli": 6.15.0
    eslint: 9.36.0
    eslint-plugin-format: 1.0.2
    "@luxass/spectral-ruleset": 1.1.0
    "@typescript-eslint/utils": 8.44.1
    "@eslint-react/eslint-plugin": 1.53.1
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-react-refresh: 0.4.21

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils": 0.11.0
    "@luxass/unicode-utils-new": npm:@luxass/unicode-utils@0.12.0-beta.11
    "@luxass/utils": 2.7.2
    farver: 0.4.2
    yargs-parser: 22.0.0
    defu: 6.1.4
    zod: 4.1.11
    "@ai-sdk/openai": 2.0.32
    ai: 5.0.48
    knitwork: 1.2.0
    picomatch: 4.0.3
    apache-autoindex-parse: 3.0.3
    openapi-fetch: 0.14.0
    pathe: 2.0.3
    "@clack/prompts": 1.0.0-alpha.5
    debug: 4.4.3

  dev:
    tsdown: 0.15.4
    typescript: 5.9.2
    publint: 0.3.13
    nanotar: 0.2.0
    openapi-typescript: 7.9.1
    tsx: 4.20.5
    memfs: 4.43.0

  workers:
    wrangler: 4.38.0
    "@hono/zod-openapi": 1.1.3
    "@scalar/hono-api-reference": 0.9.19
    hono: 4.9.8
    "@cloudflare/workers-types": 4.20250922.0

  types:
    "@types/picomatch": 4.0.2
    "@types/node": 22.18.6
    "@types/yargs-parser": 21.0.3
    "@types/react": 19.1.13
    "@types/react-dom": 19.1.9
    "@types/debug": 4.1.12
    "@types/vscode": 1.104.0

  web:
    react: 19.1.1
    react-dom: 19.1.1
    tailwindcss: 4.1.13
    "@tailwindcss/vite": 4.1.13
    "@vitejs/plugin-react": 5.0.3
    vite: 7.1.7
    "@cloudflare/vite-plugin": 1.13.3
    "@tanstack/react-router": 1.131.50
    "@tanstack/react-router-devtools": 1.131.50
    "@tanstack/router-plugin": 1.131.50

  vscode:
    vscode-ext-gen: 1.2.1
    reactive-vscode: 0.3.2
    "@reactive-vscode/vueuse": 0.3.2
    "@vscode/vsce": 3.6.0

  docs:
    docus: 5.0.0
    nuxt: 4.1.2
    better-sqlite3: 12.2.0
    "@nuxt/content": 3.7.1
    "@nuxt/eslint": 1.9.0
    "@nuxt/test-utils": 3.19.2
    "@nuxt/ui": 4.0.0
    vue-tsc: 3.1.0

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd
  - better-sqlite3

overrides:
  "@asteasolutions/zod-to-openapi": 8.1.0
  openapi-fetch: 0.14.0

patchedDependencies:
  "@asteasolutions/zod-to-openapi@8.1.0": patches/@asteasolutions__zod-to-openapi@8.1.0.patch
  openapi-fetch: patches/openapi-fetch.patch
