packages:
  - packages/*
  - apps/*
  - tooling/*

catalogs:
  dev:
    '@types/node': ^22.16.5
    '@types/picomatch': ^4.0.2
    '@types/yargs-parser': ^21.0.3
    memfs: ^4.34.0
    nanotar: ^0.2.0
    openapi-typescript: ^7.8.0
    publint: ^0.3.12
    tsdown: ^0.13.1
    tsx: ^4.20.3
    typescript: 5.8.3
  linting:
    '@eslint-react/eslint-plugin': ^1.52.3
    '@luxass/eslint-config': ^5.2.5
    '@luxass/spectral-ruleset': ^1.1.0
    '@stoplight/spectral-cli': ^6.15.0
    '@typescript-eslint/utils': ^8.38.0
    eslint: ^9.32.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
  monorepo:
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.29.5
    turbo: ^2.5.5
  prod:
    '@ai-sdk/openai': ^1.3.23
    '@clack/prompts': ^0.11.0
    '@luxass/unicode-utils': ^0.9.0
    '@luxass/unicode-utils-new': npm:@luxass/unicode-utils@0.12.0-beta.9
    '@luxass/utils': ^2.6.2
    ai: ^4.3.19
    apache-autoindex-parse: ^3.0.2
    arktype: ^2.1.20
    defu: ^6.1.4
    farver: ^0.4.2
    knitwork: ^1.2.0
    openapi-fetch: ^0.14.0
    p-limit: ^6.2.0
    pathe: ^2.0.3
    picomatch: ^4.0.3
    yargs-parser: ^22.0.0
    zod: ^4.0.14
  testing:
    '@cloudflare/vitest-pool-workers': ^0.8.59
    '@vitest/coverage-istanbul': ^3.2.4
    '@vitest/ui': ^3.2.4
    msw: ^2.10.4
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
  types:
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
  web:
    '@cloudflare/vite-plugin': ^1.11.0
    '@tailwindcss/vite': ^4.1.11
    '@tanstack/react-router': ^1.130.12
    '@tanstack/react-router-devtools': ^1.130.13
    '@tanstack/router-plugin': ^1.130.15
    '@vitejs/plugin-react': ^4.7.0
    react: ^19.1.1
    react-dom: ^19.1.1
    tailwindcss: ^4.1.11
    vite: ^7.0.6
  workers:
    '@cloudflare/workers-types': ^4.20250802.0
    '@hono/zod-openapi': ^1.0.2
    '@scalar/hono-api-reference': ^0.9.13
    hono: ^4.8.12
    wrangler: ^4.27.0

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd

patchedDependencies:
  openapi-fetch: patches/openapi-fetch.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: false
