packages:
  - packages/*

catalogs:
  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.4
    turbo: ^2.5.4
    msw: ^2.10.1
    "@vitest/coverage-v8": ^3.2.2
    "@vitest/ui": ^3.2.2
    "@ark/attest": ^0.48.2
    tsx: ^4.19.4

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils": ^0.9.0
    "@luxass/unicode-utils-new": npm:@luxass/unicode-utils@0.12.0-beta.6
    "@luxass/utils": ^2.3.0
    farver: ^0.4.2
    fs-extra: ^11.3.0
    yargs-parser: ^22.0.0
    defu: ^6.1.4
    arktype: ^2.1.20
    zod: ^3.25.56
    "@ai-sdk/openai": ^1.3.22
    ai: ^4.3.16
    p-limit: ^6.2.0
    knitwork: ^1.2.0
    picomatch: ^4.0.2

  dev:
    "@luxass/eslint-config": ^4.19.0
    "@types/fs-extra": ^11.0.4
    "@types/picomatch": ^4.0.0
    "@types/node": ^22.10.0
    "@types/yargs-parser": ^21.0.3
    eslint: ^9.28.0
    tsdown: ^0.12.7
    typescript: ^5.8.3
    vitest: ^3.2.2
    vitest-testdirs: ^4.0.0
    tsx: ^4.19.4
    publint: ^0.3.12

onlyBuiltDependencies:
  - esbuild
  - rolldown
