preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
strictPeerDependencies: false
engineStrict: false
minimumReleaseAge: 1440 # 1 day
trustPolicy: "no-downgrade"

minimumReleaseAgeExclude:
  - "@luxass/eslint-config"
  - "@luxass/msw-utils"
  - apache-autoindex-parse

  # Unicode Related Packages
  - "@unicode-utils/*"
  - "@ucdjs/*"

packages:
  - "packages/**"
  - "apps/*"
  - "tooling/*"
  - "vscode"

catalogs:
  build:
    turbo: 2.8.10
    "@ucdjs/release-scripts": 0.1.0-beta.56
    tsdown: 0.20.3
    typescript: 5.9.3
    publint: 0.3.17
    nanotar: 0.3.0
    openapi-typescript: 7.13.0
    tsx: 4.21.0
    rolldown: 1.0.0-rc.5
    "@rollup/plugin-babel": 6.1.0
    babel-plugin-react-compiler: 1.0.0
    vite-plugin-inspect: 11.3.3
    tailwindcss: 4.2.0
    "@tailwindcss/vite": 4.2.0
    "@vitejs/plugin-react": 5.1.4
    vite: 8.0.0-beta.14
    "@cloudflare/vite-plugin": 1.25.1
    "@tanstack/router-plugin": 1.161.1
    "@tanstack/devtools-vite": 0.5.1
    vite-tsconfig-paths: 6.1.1
    chokidar: 5.0.0
    drizzle-kit: 0.31.9
    esrap: 2.2.3
    oxc-parser: 0.114.0
    oxc-transform: 0.114.0
    tinyglobby: 0.2.15

  test:
    "@vitest/coverage-istanbul": 4.1.0-beta.1
    "@vitest/expect": 4.1.0-beta.1
    "@vitest/ui": 4.1.0-beta.1
    vitest: 4.1.0-beta.1
    vitest-testdirs: 4.4.2
    msw: 2.12.10
    # "@cloudflare/vitest-pool-workers": 0.11.1
    "@cloudflare/vitest-pool-workers": https://pkg.pr.new/@cloudflare/vitest-pool-workers@11632

  lint:
    "@luxass/eslint-config": 7.2.0
    "@stoplight/spectral-cli": 6.15.0
    eslint: 10.0.0
    eslint-plugin-format: 1.4.0
    "@luxass/spectral-ruleset": 1.1.1
    "@typescript-eslint/utils": 8.56.0
    "@eslint-react/eslint-plugin": 2.13.0
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.5.0

  runtime:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils-old": npm:@luxass/unicode-utils@0.11.0
    "@unicode-utils/core": 0.12.0-beta.19
    "@luxass/utils": 2.7.3
    farver: 0.4.2
    yargs-parser: 22.0.0
    defu: 6.1.4
    zod: 4.3.6
    "@ai-sdk/openai": 3.0.30
    ai: 6.0.91
    knitwork: 1.3.0
    picomatch: 4.0.3
    apache-autoindex-parse: 5.0.2
    pathe: 2.0.3
    "@clack/prompts": 1.0.1
    obug: 2.1.1
    "@luxass/msw-utils": 0.6.0
    hookable: 6.0.1
    cac: 6.7.14
    shiki: 3.22.0

  backend:
    wrangler: 4.66.0
    "@hono/zod-openapi": 1.2.2
    "@scalar/hono-api-reference": 0.9.41
    hono: 4.11.10
    "@cloudflare/workers-types": 4.20260218.0
    "@sentry/cloudflare": 10.39.0
    h3: 2.0.1-rc.14
    crossws: 0.4.4
    drizzle-orm: 0.45.1
    "@libsql/client": 0.17.0
    miniflare: 4.20260217.0

  types:
    "@types/picomatch": 4.0.2
    "@types/node": 22.19.9
    "@types/yargs-parser": 21.0.3
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    "@types/vscode": 1.109.0
    "@types/mdx": 2.0.13

  frontend:
    react: 19.2.4
    react-dom: 19.2.4
    "@tanstack/react-router": 1.161.1
    "@tanstack/react-router-devtools": 1.161.1
    "@tanstack/zod-adapter": 1.161.1
    "@tanstack/react-devtools": 0.9.6
    "@tanstack/react-form": 1.28.3
    "@tanstack/react-query": 5.90.21
    "@tanstack/react-query-devtools": 5.91.3
    "@tanstack/react-router-ssr-query": 1.161.1
    "@tanstack/react-start": 1.161.1
    lucide-react: 0.574.0
    "@icons-pack/react-simple-icons": 13.11.2
    nitro: 3.0.1-alpha.2
    tw-animate-css: 1.4.0
    tailwind-merge: 3.4.1
    clsx: 2.1.1
    class-variance-authority: 0.7.1
    "@base-ui/react": 1.2.0
    "@base-ui/utils": 0.2.5
    "@fontsource-variable/inter": 5.2.8
    "@xyflow/react": 12.10.0

  vscode:
    vscode-ext-gen: 1.5.1
    reactive-vscode: 1.0.0-beta.2
    "@reactive-vscode/vueuse": 1.0.0-beta.2
    "@vscode/vsce": 3.7.1

  docs:
    fumadocs-mdx: 14.2.7
    fumadocs-core: 16.6.3
    fumadocs-ui: 16.6.3

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd

overrides:
  "@asteasolutions/zod-to-openapi": 8.4.1
  rolldown: catalog:build
  wrangler: catalog:backend
  miniflare: catalog:backend
  esbuild: 0.27.3
  semver: 7.7.4
  solid-js: 1.9.11
  undici-types: 7.22.0

patchedDependencies:
  "@asteasolutions/zod-to-openapi@8.4.1": patches/@asteasolutions__zod-to-openapi@8.4.1.patch
