preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - "@luxass/eslint-config"
  - "@luxass/unicode-utils"
  - "@luxass/msw-utils"
  - apache-autoindex-parse

packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
  - "vscode"

catalogs:
  monorepo:
    "@changesets/changelog-github": 0.5.1
    "@changesets/cli": 2.29.7
    turbo: 2.5.8

  testing:
    "@vitest/coverage-istanbul": 3.2.4
    "@vitest/ui": 3.2.4
    vitest: 3.2.4
    vitest-testdirs: 4.2.1
    msw: 2.11.6
    "@cloudflare/vitest-pool-workers": 0.9.13

  linting:
    "@luxass/eslint-config": 6.0.1
    "@stoplight/spectral-cli": 6.15.0
    eslint: 9.38.0
    eslint-plugin-format: 1.0.2
    "@luxass/spectral-ruleset": 1.1.0
    "@typescript-eslint/utils": 8.46.2
    "@eslint-react/eslint-plugin": 2.2.2
    eslint-plugin-react-hooks: 7.0.0
    eslint-plugin-react-refresh: 0.4.24

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils-old": npm:@luxass/unicode-utils@0.11.0
    "@luxass/unicode-utils": 0.12.0-beta.14
    "@luxass/utils": 2.7.2
    destr: 2.0.5
    farver: 0.4.2
    yargs-parser: 22.0.0
    defu: 6.1.4
    zod: 4.1.11
    "@ai-sdk/openai": 2.0.32
    ai: 5.0.48
    knitwork: 1.2.0
    picomatch: 4.0.3
    apache-autoindex-parse: 4.0.3
    pathe: 2.0.3
    "@clack/prompts": 1.0.0-alpha.5
    debug: 4.4.3
    "@luxass/msw-utils": 0.4.0
    hookable: 5.5.3

  dev:
    tsdown: 0.15.9
    typescript: 5.9.3
    publint: 0.3.15
    nanotar: 0.2.0
    openapi-typescript: 7.10.1
    tsx: 4.20.6
    rolldown: 1.0.0-beta.44

  workers:
    wrangler: 4.43.0
    "@hono/zod-openapi": 1.1.4
    "@scalar/hono-api-reference": 0.9.22
    hono: 4.10.1
    "@cloudflare/workers-types": 4.20251014.0

  types:
    "@types/picomatch": 4.0.2
    "@types/node": 22.18.12
    "@types/yargs-parser": 21.0.3
    "@types/react": 19.2.2
    "@types/react-dom": 19.2.2
    "@types/debug": 4.1.12
    "@types/vscode": 1.104.0

  web:
    react: 19.2.0
    react-dom: 19.2.0
    tailwindcss: 4.1.15
    "@tailwindcss/vite": 4.1.15
    "@vitejs/plugin-react": 5.0.4
    vite: 7.1.11
    "@cloudflare/vite-plugin": 1.13.13
    "@tanstack/react-router": 1.133.20
    "@tanstack/react-router-devtools": 1.133.20
    "@tanstack/router-plugin": 1.133.20

  vscode:
    vscode-ext-gen: 1.2.1
    reactive-vscode: 0.3.2
    "@reactive-vscode/vueuse": 0.3.2
    "@vscode/vsce": 3.6.0

  docs:
    docus: 5.1.0
    nuxt: 4.1.2
    better-sqlite3: 12.2.0
    "@nuxt/content": 3.7.1
    "@nuxt/eslint": 1.9.0
    "@nuxt/test-utils": 3.19.2
    "@nuxt/ui": 4.0.0
    vue-tsc: 3.1.0

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd
  - better-sqlite3

overrides:
  "@asteasolutions/zod-to-openapi": 8.1.0
  rolldown: catalog:dev

patchedDependencies:
  "@asteasolutions/zod-to-openapi@8.1.0": patches/@asteasolutions__zod-to-openapi@8.1.0.patch
