preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - "@luxass/eslint-config"
  - "@luxass/msw-utils"
  - apache-autoindex-parse

  # Unicode Related Packages
  - "@unicode-utils/*"
  - "@ucdjs/*"

packages:
  - "packages/**"
  - "apps/*"
  - "tooling/*"
  - "vscode"

catalogs:
  monorepo:
    turbo: 2.8.1
    "@ucdjs/release-scripts": 0.1.0-beta.24

  testing:
    "@vitest/coverage-istanbul": 4.1.0-beta.1
    "@vitest/expect": 4.1.0-beta.1
    "@vitest/ui": 4.1.0-beta.1
    vitest: 4.1.0-beta.1
    vitest-testdirs: 4.4.2
    msw: 2.12.7
    # "@cloudflare/vitest-pool-workers": 0.11.1
    "@cloudflare/vitest-pool-workers": https://pkg.pr.new/@cloudflare/vitest-pool-workers@11632

  linting:
    "@luxass/eslint-config": 7.0.0
    "@stoplight/spectral-cli": 6.15.0
    eslint: 9.39.2
    eslint-plugin-format: 1.3.1
    "@luxass/spectral-ruleset": 1.1.1
    "@typescript-eslint/utils": 8.54.0
    "@eslint-react/eslint-plugin": 2.8.1
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.26

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils-old": npm:@luxass/unicode-utils@0.11.0
    "@unicode-utils/core": 0.12.0-beta.19
    "@luxass/utils": 2.7.2
    farver: 0.4.2
    yargs-parser: 22.0.0
    defu: 6.1.4
    zod: 4.3.6
    "@ai-sdk/openai": 3.0.23
    ai: 6.0.64
    knitwork: 1.3.0
    picomatch: 4.0.3
    apache-autoindex-parse: 5.0.2
    pathe: 2.0.3
    "@clack/prompts": 1.0.0
    obug: 2.1.1
    "@luxass/msw-utils": 0.6.0
    hookable: 6.0.1
    cac: 6.7.14

  build:
    tsdown: 0.20.1
    typescript: 5.9.3
    publint: 0.3.17
    nanotar: 0.2.0
    openapi-typescript: 7.10.1
    tsx: 4.21.0
    rolldown: 1.0.0-rc.2

  api:
    wrangler: 4.61.1
    "@hono/zod-openapi": 1.2.0
    "@scalar/hono-api-reference": 0.9.39
    hono: 4.11.7
    "@cloudflare/workers-types": 4.20260131.0
    "@sentry/cloudflare": 10.38.0

  types:
    "@types/picomatch": 4.0.2
    "@types/node": 22.18.12
    "@types/yargs-parser": 21.0.3
    "@types/react": 19.2.10
    "@types/react-dom": 19.2.3
    "@types/vscode": 1.108.1
    "@types/mdx": 2.0.13

  web:
    react: 19.2.4
    react-dom: 19.2.4
    tailwindcss: 4.1.18
    "@tailwindcss/vite": 4.1.18
    "@vitejs/plugin-react": 5.1.2
    vite: 7.3.1
    "@cloudflare/vite-plugin": 1.22.1
    "@tanstack/react-router": 1.157.17
    "@tanstack/react-router-devtools": 1.157.17
    "@tanstack/router-plugin": 1.157.17
    "@tanstack/zod-adapter": 1.157.17
    "@tanstack/react-devtools": 0.9.4
    "@tanstack/react-form": 1.28.0
    "@tanstack/react-query": 5.90.20
    "@tanstack/react-query-devtools": 5.91.3
    "@tanstack/react-router-ssr-query": 1.157.17
    "@tanstack/react-start": 1.157.17
    "@tanstack/devtools-vite": 0.5.0
    lucide-react: 0.563.0
    nitro: 3.0.1-alpha.2
    vite-tsconfig-paths: 6.0.5
    babel-plugin-react-compiler: 1.0.0
    tw-animate-css: 1.4.0
    tailwind-merge: 3.4.0
    shadcn: 3.8.1
    clsx: 2.1.1
    class-variance-authority: 0.7.1
    "@base-ui/react": 1.1.0
    "@fontsource-variable/inter": 5.2.8
    shiki: 3.22.0
    cmdk: 1.1.1

  vscode:
    vscode-ext-gen: 1.5.1
    reactive-vscode: 1.0.0-beta.2
    "@reactive-vscode/vueuse": 1.0.0-beta.2
    "@vscode/vsce": 3.7.1

  docs:
    fumadocs-mdx: 14.2.6
    fumadocs-core: 16.4.11
    fumadocs-ui: 16.4.11

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd

overrides:
  "@asteasolutions/zod-to-openapi": 8.4.0
  rolldown: catalog:build
  wrangler: catalog:api

patchedDependencies:
  "@asteasolutions/zod-to-openapi@8.4.0": patches/@asteasolutions__zod-to-openapi@8.4.0.patch
