preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - "@luxass/eslint-config"
  - "@luxass/msw-utils"
  - apache-autoindex-parse

  # Unicode Related Packages
  - "@unicode-utils/*"
  - "@ucdjs/*"

packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
  - "vscode"

catalogs:
  monorepo:
    turbo: 2.6.3
    "@ucdjs/release-scripts": 0.1.0-beta.24

  testing:
    "@vitest/coverage-istanbul": 3.2.4
    "@vitest/ui": 3.2.4
    vitest: 3.2.4
    vitest-testdirs: 4.3.0
    msw: 2.12.4
    "@cloudflare/vitest-pool-workers": 0.9.13

  linting:
    "@luxass/eslint-config": 6.0.3
    "@stoplight/spectral-cli": 6.15.0
    eslint: 9.39.1
    eslint-plugin-format: 1.1.0
    "@luxass/spectral-ruleset": 1.1.0
    "@typescript-eslint/utils": 8.48.1
    "@eslint-react/eslint-plugin": 2.3.12
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.24

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils-old": npm:@luxass/unicode-utils@0.11.0
    "@unicode-utils/core": 0.12.0-beta.18
    "@luxass/utils": 2.7.2
    farver: 0.4.2
    yargs-parser: 22.0.0
    defu: 6.1.4
    zod: 4.1.13
    "@ai-sdk/openai": 2.0.77
    ai: 5.0.108
    knitwork: 1.3.0
    picomatch: 4.0.3
    apache-autoindex-parse: 4.1.0
    pathe: 2.0.3
    "@clack/prompts": 1.0.0-alpha.7
    obug: 2.1.1
    "@luxass/msw-utils": 0.4.0
    hookable: 6.0.0-rc.1

  dev:
    tsdown: 0.17.2
    typescript: 5.9.3
    publint: 0.3.16
    nanotar: 0.2.0
    openapi-typescript: 7.10.1
    tsx: 4.21.0
    rolldown: 1.0.0-beta.54

  workers:
    wrangler: 4.54.0
    "@hono/zod-openapi": 1.1.5
    "@scalar/hono-api-reference": 0.9.28
    hono: 4.10.8
    "@cloudflare/workers-types": 4.20251210.0

  types:
    "@types/picomatch": 4.0.2
    "@types/node": 22.18.12
    "@types/yargs-parser": 21.0.3
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3
    "@types/vscode": 1.106.1
    "@types/mdx": 2.0.13

  web:
    react: 19.2.3
    react-dom: 19.2.3
    tailwindcss: 4.1.18
    "@tailwindcss/vite": 4.1.18
    "@vitejs/plugin-react": 5.1.2
    vite: 7.2.7
    "@cloudflare/vite-plugin": 1.17.1
    "@tanstack/react-router": 1.140.1
    "@tanstack/react-router-devtools": 1.140.1
    "@tanstack/router-plugin": 1.140.1
    "@tanstack/react-devtools": 0.8.4
    "@tanstack/react-form": 1.27.2
    "@tanstack/react-query": 5.90.12
    "@tanstack/react-query-devtools": 5.91.1
    "@tanstack/react-router-ssr-query": 1.140.1
    "@tanstack/react-start": 1.140.3
    "@tanstack/devtools-vite": 0.3.12
    lucide-react: 0.559.0
    nitro: 3.0.1-alpha.1
    vite-tsconfig-paths: 5.1.4
    babel-plugin-react-compiler: 1.0.0
    tw-animate-css: 1.4.0
    tailwind-merge: 3.4.0
    shadcn: 3.6.1
    clsx: 2.1.1
    class-variance-authority: 0.7.1
    "@base-ui/react": 1.0.0
    "@fontsource-variable/inter": 5.2.8

  vscode:
    vscode-ext-gen: 1.4.0
    reactive-vscode: 0.4.1
    "@reactive-vscode/vueuse": 0.4.1
    "@vscode/vsce": 3.7.1

  docs:
    fumadocs-mdx: 14.1.1
    fumadocs-core: 16.2.5
    fumadocs-ui: 16.2.5

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd

overrides:
  "@asteasolutions/zod-to-openapi": 8.2.0
  rolldown: catalog:dev

patchedDependencies:
  "@asteasolutions/zod-to-openapi@8.2.0": patches/@asteasolutions__zod-to-openapi@8.2.0.patch
