preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true

packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalogs:
  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.4
    turbo: ^2.5.4
    "@ark/attest": ^0.48.2

  testing:
    "@vitest/coverage-istanbul": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.0
    msw: ^2.10.1
    "@cloudflare/vitest-pool-workers": ^0.8.43

  linting:
    "@luxass/eslint-config": ^5.0.0
    "@stoplight/spectral-cli": ^6.15.0
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    "@luxass/spectral-ruleset": ^1.0.0

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils": ^0.9.0
    "@luxass/unicode-utils-new": npm:@luxass/unicode-utils@0.12.0-beta.8
    "@luxass/utils": ^2.4.1
    farver: ^0.4.2
    yargs-parser: ^22.0.0
    defu: ^6.1.4
    arktype: ^2.1.20
    zod: ^3.25.56
    "@ai-sdk/openai": ^1.3.22
    ai: ^4.3.16
    p-limit: ^6.2.0
    knitwork: ^1.2.0
    picomatch: ^4.0.2
    memfs: ^4.17.2
    apache-autoindex-parse: ^2.0.0
    openapi-fetch: ^0.14.0

  dev:
    "@types/picomatch": ^4.0.0
    "@types/node": ^22.10.0
    "@types/yargs-parser": ^21.0.3
    tsdown: ^0.12.7
    typescript: ^5.8.3
    publint: ^0.3.12
    nanotar: ^0.2.0
    openapi-typescript: ^7.8.0
    tsx: ^4.19.4

  workers:
    wrangler: ^4.20.5
    "@hono/zod-openapi": ^0.19.8
    "@scalar/hono-api-reference": ^0.9.6
    hono: ^4.8.2

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd
