preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
patchedDependencies:
  '@hono/zod-openapi': patches/@hono__zod-openapi.patch

packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalogs:
  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.5
    turbo: ^2.5.5

  testing:
    "@vitest/coverage-istanbul": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
    msw: ^2.10.4
    "@cloudflare/vitest-pool-workers": ^0.8.55

  linting:
    "@luxass/eslint-config": ^5.1.1
    "@stoplight/spectral-cli": ^6.15.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    "@luxass/spectral-ruleset": ^1.1.0

  prod:
    # merge these together when heading inference is implemented better
    "@luxass/unicode-utils": ^0.9.0
    "@luxass/unicode-utils-new": npm:@luxass/unicode-utils@0.12.0-beta.9
    "@luxass/utils": ^2.6.0
    farver: ^0.4.2
    yargs-parser: ^22.0.0
    defu: ^6.1.4
    arktype: ^2.1.20
    zod: ^4.0.5
    "@ai-sdk/openai": ^1.3.22
    ai: ^4.3.16
    p-limit: ^6.2.0
    knitwork: ^1.2.0
    picomatch: ^4.0.2
    memfs: ^4.17.2
    apache-autoindex-parse: ^2.3.0
    openapi-fetch: ^0.14.0

  dev:
    "@types/picomatch": ^4.0.0
    "@types/node": ^22.10.0
    "@types/yargs-parser": ^21.0.3
    tsdown: ^0.12.9
    typescript: ^5.8.3
    publint: ^0.3.12
    nanotar: ^0.2.0
    openapi-typescript: ^7.8.0
    tsx: ^4.20.3

  workers:
    wrangler: ^4.25.0
    "@hono/zod-openapi": ^1.0.2
    "@scalar/hono-api-reference": ^0.9.11
    hono: ^4.8.5

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - workerd
