import process from "node:process";
import { CLI_NAME, parseCommand, printCommandHelp } from "#lib/command";
import { getMonorepoRoot } from "#lib/utils";
import { createReleaseScripts } from "@ucdjs/release-scripts";

/** @typedef {import("../lib/command.js").CommandDefinition} CommandDefinition */

const releasePullRequestBody = `
  This PR was automatically generated by the UCD release scripts.

  The following packages have been prepared for release:

  <% if (it.packages.length > 0) { %>
  <% it.packages.forEach((pkg) => { %>
  - **<%= pkg.name %>**: <%= pkg.currentVersion %> → <%= pkg.newVersion %> (<%= pkg.bumpType %>)
  <% }) %>
  <% } else { %>
  There are no packages to release.
  <% } %>

  Please review the changes and merge when ready.

  > [!NOTE]
  > When this PR is merged, the release process will be triggered automatically, publishing the new package versions to the registry.
`;

const VALID_RELEASE_COMMANDS = new Set(["prepare", "verify", "publish"]);

async function createCommands() {
  return createReleaseScripts({
    repo: "ucdjs/ucd",
    workspaceRoot: getMonorepoRoot(),
    packages: {
      excludePrivate: true,
      exclude: ["vscode-ucd"],
    },
    githubToken: process.env.UCDJS_RELEASE_TOKEN ?? "",
    types: {
      feat: { title: "🚀 Features" },
      fix: { title: "🐞 Bug Fixes" },
      perf: { title: "🏎 Performance" },
      docs: { title: "📚 Documentation" },
      style: { title: "🎨 Styles" },
    },
    globalCommitMode: "dependencies",
    pullRequest: {
      body: releasePullRequestBody,
    },
    changelog: {
      enabled: true,
      emojis: true,
      combinePrereleaseIntoFirstStable: true,
    },
    npm: {
      provenance: true,
      access: "public",
    },
  });
}

/**
 * @param {string[]} args
 * @returns {Promise<void>}
 */
export async function runReleaseCommand(args) {
  const parsed = parseCommand(args, {
      usage: `$ ${CLI_NAME} release <prepare|verify|publish>`,
      description: "Run the release workflow against the current workspace.",
      commands: [
        {
          name: "prepare",
          description: "Create or update the release PR",
        },
        {
          name: "verify",
          description: "Verify the release branch state",
        },
        {
          name: "publish",
          description: "Publish releasable packages to npm",
        },
      ],
    }, { allowPositionals: true });
  if (!parsed) {
    return;
  }

  if (parsed.positionals.length !== 1) {
    console.error("Missing release command.");
    printCommandHelp({
        usage: `$ ${CLI_NAME} release <prepare|verify|publish>`,
        description: "Run the release workflow against the current workspace.",
        commands: [
          {
            name: "prepare",
            description: "Create or update the release PR",
          },
          {
            name: "verify",
            description: "Verify the release branch state",
          },
          {
            name: "publish",
            description: "Publish releasable packages to npm",
          },
        ],
      });
    process.exit(1);
  }

  const releaseCommandName = parsed.positionals[0];

  if (!releaseCommandName || !VALID_RELEASE_COMMANDS.has(releaseCommandName)) {
    console.error(`Unknown release command "${releaseCommandName}".`);
    printCommandHelp({
        usage: `$ ${CLI_NAME} release <prepare|verify|publish>`,
        description: "Run the release workflow against the current workspace.",
        commands: [
          {
            name: "prepare",
            description: "Create or update the release PR",
          },
          {
            name: "verify",
            description: "Verify the release branch state",
          },
          {
            name: "publish",
            description: "Publish releasable packages to npm",
          },
        ],
      });
    process.exit(1);
  }

  const { prepare, verify, publish } = await createCommands();

  switch (releaseCommandName) {
    case "prepare":
      await prepare();
      return;
    case "verify":
      await verify();
      return;
    case "publish":
      await publish();
      return;
  }
}
