import { getRouteApi } from "@tanstack/react-router";

const PipelineRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId");
const InspectRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId/inspect");
const InspectIndexRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId/inspect/");

export function RouteOutputsSection() {
  const params = InspectIndexRoute.useParams();
  const navigate = InspectIndexRoute.useNavigate();
  const search = InspectRoute.useSearch();
  const { pipelineResponse } = PipelineRoute.useLoaderData();
  const selectedRoute = pipelineResponse.pipeline.routes.find((route) => route.id === search.route)
    ?? pipelineResponse.pipeline.routes[0]
    ?? null;

  function openOutput(outputIndex: number) {
    if (!selectedRoute) {
      return;
    }

    navigate({
      to: "/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs",
      params,
      search: (current) => ({
        q: current.q,
        route: selectedRoute.id,
        transform: undefined,
        output: `${selectedRoute.id}:${outputIndex}`,
      }),
    });
  }

  return (
    <section className="space-y-3">
      <div>
        <h3 className="text-xs uppercase tracking-wide text-muted-foreground">Outputs</h3>
        <p className="text-sm text-muted-foreground">
          Output definitions describe where this route writes artifacts, not the runtime files it produced.
        </p>
      </div>
      {selectedRoute?.outputs.length
        ? (
            <div className="grid gap-3 md:grid-cols-2">
              {selectedRoute.outputs.map((output, index) => (
                <div key={`${output.dir ?? "none"}-${output.fileName ?? "none"}-${index}`} className="rounded-lg border border-border/60 bg-muted/10 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div className="text-sm font-medium">
                      Output
                      {index + 1}
                    </div>
                    <button
                      type="button"
                      onClick={() => openOutput(index)}
                      className="inline-flex items-center rounded-md border border-border px-2.5 py-1 text-xs font-medium text-foreground transition-colors hover:bg-muted"
                    >
                      Open output
                    </button>
                  </div>
                  <div className="mt-3 grid gap-3">
                    <div className="space-y-1">
                      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Directory</div>
                      <div className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
                        {output.dir ?? "Default route output directory"}
                      </div>
                    </div>
                    <div className="space-y-1">
                      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">File name</div>
                      <div className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
                        {output.fileName ?? "Generated by route configuration"}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )
        : (
            <div className="rounded-md border border-dashed border-border/70 px-4 py-8 text-sm text-muted-foreground">
              No output definitions for this route.
            </div>
          )}
    </section>
  );
}
