import type { PipelineDetails } from "#shared/schemas/pipeline";
import { Link, useParams } from "@tanstack/react-router";
import { Card, CardContent, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { ArrowRight, FolderOutput } from "lucide-react";

export interface RouteOutputsSectionProps {
  route: PipelineDetails["routes"][number];
}

export function RouteOutputsSection({ route }: RouteOutputsSectionProps) {
  const { sourceId, sourceFileId, pipelineId } = useParams({ from: "/s/$sourceId/$sourceFileId/$pipelineId" });

  return (
    <Card>
      <CardHeader className="border-b border-border/60 pb-4">
        <div className="flex items-center gap-2">
          <FolderOutput className="h-4 w-4 text-muted-foreground" />
          <CardTitle className="text-base">Outputs</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="pt-5">
        {route.outputs.length
          ? (
              <div className="grid gap-3">
                {/* Outputs are positional — index is the canonical key (used as outputKey param) */}
                {route.outputs.map((output, index) => (
                  // eslint-disable-next-line react/no-array-index-key
                  <div key={index} className="rounded-lg border border-border/60 p-4">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-medium">
                        Output
                        {index + 1}
                      </div>
                      <Link
                        to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs/$outputKey"
                        params={{ sourceId, sourceFileId, pipelineId, outputKey: `${route.id}:${index}` }}
                        className="inline-flex h-8 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-sm font-medium shadow-xs hover:bg-accent hover:text-accent-foreground"
                      >
                        Open output
                        <ArrowRight className="h-3 w-3" />
                      </Link>
                    </div>
                    <div className="mt-3 grid gap-3 sm:grid-cols-2">
                      <div className="space-y-1">
                        <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Directory</div>
                        <div className="text-sm text-foreground">{output.dir ?? "Default route output directory"}</div>
                      </div>
                      <div className="space-y-1">
                        <div className="text-[11px] uppercase tracking-wide text-muted-foreground">File name</div>
                        <div className="text-sm text-foreground">{output.fileName ?? "Generated by route configuration"}</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )
          : (
              <div className="rounded-md border border-dashed border-border/70 px-4 py-8 text-sm text-muted-foreground">
                No output definitions for this route.
              </div>
            )}
      </CardContent>
    </Card>
  );
}
