import { useInspectData } from "#hooks/use-inspect-data";
import { Button } from "@ucdjs-internal/shared-ui/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { ArrowRight, FolderOutput } from "lucide-react";

export function RouteOutputsSection() {
  const { selectedRoute, navigateToOutput } = useInspectData();

  if (!selectedRoute) return null;

  return (
    <Card>
      <CardHeader className="border-b border-border/60 pb-4">
        <div className="flex items-center gap-2">
          <FolderOutput className="h-4 w-4 text-muted-foreground" />
          <CardTitle className="text-base">Outputs</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="pt-5">
        {selectedRoute.outputs.length
          ? (
              <div className="grid gap-3">
                {selectedRoute.outputs.map((output, index) => (
                  <div key={`${output.dir ?? "none"}-${output.fileName ?? "none"}-${index}`} className="rounded-lg border border-border/60 p-4">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-medium">
                        Output
                        {index + 1}
                      </div>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => navigateToOutput(selectedRoute.id, index)}
                      >
                        Open output
                        <ArrowRight className="h-3 w-3" />
                      </Button>
                    </div>
                    <div className="mt-3 grid gap-3 sm:grid-cols-2">
                      <div className="space-y-1">
                        <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Directory</div>
                        <div className="text-sm text-foreground">{output.dir ?? "Default route output directory"}</div>
                      </div>
                      <div className="space-y-1">
                        <div className="text-[11px] uppercase tracking-wide text-muted-foreground">File name</div>
                        <div className="text-sm text-foreground">{output.fileName ?? "Generated by route configuration"}</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )
          : (
              <div className="rounded-md border border-dashed border-border/70 px-4 py-8 text-sm text-muted-foreground">
                No output definitions for this route.
              </div>
            )}
      </CardContent>
    </Card>
  );
}
