import type { ReactNode } from "react";
import { Button } from "@ucdjs-internal/shared-ui/components";
import { Eye, EyeOff } from "lucide-react";
import { useState } from "react";

interface MinimalOutputCardProps {
  title: string;
  output: {
    sink: string;
    path?: string;
    dynamicPath?: boolean;
    pathSource?: string;
    dir?: string;
    fileName?: string;
  };
  action?: ReactNode;
}

export function MinimalOutputCard({ title, output, action }: MinimalOutputCardProps) {
  const [pathExpanded, setPathExpanded] = useState(false);

  return (
    <div className="rounded-lg border border-border/60 bg-muted/10 p-4" data-testid="minimal-output-card">
      <div className="flex items-center justify-between gap-3">
        <div className="text-sm font-medium">{title}</div>
        {action}
      </div>
      <div className="mt-3 grid gap-3">
        <Field label="Sink">{output.sink}</Field>
        <div className="space-y-1">
          <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Path</div>
          <div className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
            <div className="flex items-start gap-3">
              {output.dynamicPath && output.pathSource
                ? (
                    <>
                      {pathExpanded
                        ? (
                            <pre className="min-w-0 flex-1 overflow-x-auto whitespace-pre-wrap break-words text-sm text-foreground">
                              {output.pathSource}
                            </pre>
                          )
                        : (
                            <code className="min-w-0 flex-1 text-sm">&lt;output fn&gt;</code>
                          )}
                      <Button
                        variant="outline"
                        size="icon-xs"
                        onClick={() => setPathExpanded((prev) => !prev)}
                        aria-label={pathExpanded ? "Hide output function" : "Show output function"}
                        title={pathExpanded ? "Hide output function" : "Show output function"}
                      >
                        {pathExpanded ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
                      </Button>
                    </>
                  )
                : (output.path ?? "Generated by route configuration")}
            </div>
          </div>
        </div>
        <div className="grid gap-3 md:grid-cols-2">
          <Field label="Directory">{output.dir ?? "Default route output directory"}</Field>
          <Field label="File name">{output.fileName ?? "Generated by route configuration"}</Field>
        </div>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="space-y-1">
      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div>
      <div className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground">
        {children}
      </div>
    </div>
  );
}
