/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FileExplorerRouteRouteImport } from './routes/file-explorer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as FileExplorerSplatRouteImport } from './routes/file-explorer/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as VVersionRouteRouteImport } from './routes/v/$version/route'
import { Route as VVersionIndexRouteImport } from './routes/v/$version/index'
import { Route as FileExplorerVSplatRouteImport } from './routes/file-explorer/v.$'
import { Route as VVersionBlocksIndexRouteImport } from './routes/v/$version/blocks/index'
import { Route as VVersionUHexRouteImport } from './routes/v/$version/u/$hex'
import { Route as VVersionBlocksIdRouteImport } from './routes/v/$version/blocks/$id'

const FileExplorerRouteRoute = FileExplorerRouteRouteImport.update({
  id: '/file-explorer',
  path: '/file-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileExplorerSplatRoute = FileExplorerSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FileExplorerRouteRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VVersionRouteRoute = VVersionRouteRouteImport.update({
  id: '/v/$version',
  path: '/v/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const VVersionIndexRoute = VVersionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VVersionRouteRoute,
} as any)
const FileExplorerVSplatRoute = FileExplorerVSplatRouteImport.update({
  id: '/v/$',
  path: '/v/$',
  getParentRoute: () => FileExplorerRouteRoute,
} as any)
const VVersionBlocksIndexRoute = VVersionBlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => VVersionRouteRoute,
} as any)
const VVersionUHexRoute = VVersionUHexRouteImport.update({
  id: '/u/$hex',
  path: '/u/$hex',
  getParentRoute: () => VVersionRouteRoute,
} as any)
const VVersionBlocksIdRoute = VVersionBlocksIdRouteImport.update({
  id: '/blocks/$id',
  path: '/blocks/$id',
  getParentRoute: () => VVersionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/v/$version': typeof VVersionRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/docs': typeof DocsIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version/': typeof VVersionIndexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks': typeof VVersionBlocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/docs': typeof DocsIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version': typeof VVersionIndexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks': typeof VVersionBlocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/v/$version': typeof VVersionRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version/': typeof VVersionIndexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks/': typeof VVersionBlocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-explorer'
    | '/v/$version'
    | '/api/search'
    | '/docs/$'
    | '/file-explorer/$'
    | '/docs'
    | '/file-explorer/v/$'
    | '/v/$version/'
    | '/v/$version/blocks/$id'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-explorer'
    | '/api/search'
    | '/docs/$'
    | '/file-explorer/$'
    | '/docs'
    | '/file-explorer/v/$'
    | '/v/$version'
    | '/v/$version/blocks/$id'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks'
  id:
    | '__root__'
    | '/'
    | '/file-explorer'
    | '/v/$version'
    | '/api/search'
    | '/docs/$'
    | '/file-explorer/$'
    | '/docs/'
    | '/file-explorer/v/$'
    | '/v/$version/'
    | '/v/$version/blocks/$id'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileExplorerRouteRoute: typeof FileExplorerRouteRouteWithChildren
  VVersionRouteRoute: typeof VVersionRouteRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/file-explorer': {
      id: '/file-explorer'
      path: '/file-explorer'
      fullPath: '/file-explorer'
      preLoaderRoute: typeof FileExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-explorer/$': {
      id: '/file-explorer/$'
      path: '/$'
      fullPath: '/file-explorer/$'
      preLoaderRoute: typeof FileExplorerSplatRouteImport
      parentRoute: typeof FileExplorerRouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$version': {
      id: '/v/$version'
      path: '/v/$version'
      fullPath: '/v/$version'
      preLoaderRoute: typeof VVersionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$version/': {
      id: '/v/$version/'
      path: '/'
      fullPath: '/v/$version/'
      preLoaderRoute: typeof VVersionIndexRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/file-explorer/v/$': {
      id: '/file-explorer/v/$'
      path: '/v/$'
      fullPath: '/file-explorer/v/$'
      preLoaderRoute: typeof FileExplorerVSplatRouteImport
      parentRoute: typeof FileExplorerRouteRoute
    }
    '/v/$version/blocks/': {
      id: '/v/$version/blocks/'
      path: '/blocks'
      fullPath: '/v/$version/blocks'
      preLoaderRoute: typeof VVersionBlocksIndexRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/u/$hex': {
      id: '/v/$version/u/$hex'
      path: '/u/$hex'
      fullPath: '/v/$version/u/$hex'
      preLoaderRoute: typeof VVersionUHexRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/blocks/$id': {
      id: '/v/$version/blocks/$id'
      path: '/blocks/$id'
      fullPath: '/v/$version/blocks/$id'
      preLoaderRoute: typeof VVersionBlocksIdRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
  }
}

interface FileExplorerRouteRouteChildren {
  FileExplorerSplatRoute: typeof FileExplorerSplatRoute
  FileExplorerVSplatRoute: typeof FileExplorerVSplatRoute
}

const FileExplorerRouteRouteChildren: FileExplorerRouteRouteChildren = {
  FileExplorerSplatRoute: FileExplorerSplatRoute,
  FileExplorerVSplatRoute: FileExplorerVSplatRoute,
}

const FileExplorerRouteRouteWithChildren =
  FileExplorerRouteRoute._addFileChildren(FileExplorerRouteRouteChildren)

interface VVersionRouteRouteChildren {
  VVersionIndexRoute: typeof VVersionIndexRoute
  VVersionBlocksIdRoute: typeof VVersionBlocksIdRoute
  VVersionUHexRoute: typeof VVersionUHexRoute
  VVersionBlocksIndexRoute: typeof VVersionBlocksIndexRoute
}

const VVersionRouteRouteChildren: VVersionRouteRouteChildren = {
  VVersionIndexRoute: VVersionIndexRoute,
  VVersionBlocksIdRoute: VVersionBlocksIdRoute,
  VVersionUHexRoute: VVersionUHexRoute,
  VVersionBlocksIndexRoute: VVersionBlocksIndexRoute,
}

const VVersionRouteRouteWithChildren = VVersionRouteRoute._addFileChildren(
  VVersionRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileExplorerRouteRoute: FileExplorerRouteRouteWithChildren,
  VVersionRouteRoute: VVersionRouteRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
