/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CodepointInspectorRouteImport } from './routes/codepoint-inspector'
import { Route as FileExplorerRouteRouteImport } from './routes/file-explorer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VIndexRouteImport } from './routes/v/index'
import { Route as FileExplorerSplatRouteImport } from './routes/file-explorer/$'
import { Route as VVersionRouteRouteImport } from './routes/v/$version/route'
import { Route as VVersionIndexRouteImport } from './routes/v/$version/index'
import { Route as FileExplorerVSplatRouteImport } from './routes/file-explorer/v.$'
import { Route as VVersionUHexRouteImport } from './routes/v/$version/u/$hex'

const VVersionNormalizationPreviewLazyRouteImport = createFileRoute(
  '/v/$version/normalization-preview',
)()
const VVersionGraphemeVisualizerLazyRouteImport = createFileRoute(
  '/v/$version/grapheme-visualizer',
)()
const VVersionFontGlyphViewLazyRouteImport = createFileRoute(
  '/v/$version/font-glyph-view',
)()
const VVersionBidiLinebreakLazyRouteImport = createFileRoute(
  '/v/$version/bidi-linebreak',
)()
const VVersionBlocksIndexLazyRouteImport = createFileRoute(
  '/v/$version/blocks/',
)()
const VVersionBlocksIdLazyRouteImport = createFileRoute(
  '/v/$version/blocks/$id',
)()

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CodepointInspectorRoute = CodepointInspectorRouteImport.update({
  id: '/codepoint-inspector',
  path: '/codepoint-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const FileExplorerRouteRoute = FileExplorerRouteRouteImport.update({
  id: '/file-explorer',
  path: '/file-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VIndexRoute = VIndexRouteImport.update({
  id: '/v/',
  path: '/v/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileExplorerSplatRoute = FileExplorerSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FileExplorerRouteRoute,
} as any)
const VVersionRouteRoute = VVersionRouteRouteImport.update({
  id: '/v/$version',
  path: '/v/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const VVersionIndexRoute = VVersionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VVersionRouteRoute,
} as any)
const VVersionNormalizationPreviewLazyRoute =
  VVersionNormalizationPreviewLazyRouteImport.update({
    id: '/normalization-preview',
    path: '/normalization-preview',
    getParentRoute: () => VVersionRouteRoute,
  } as any).lazy(() =>
    import('./routes/v/$version/normalization-preview.lazy').then(
      (d) => d.Route,
    ),
  )
const VVersionGraphemeVisualizerLazyRoute =
  VVersionGraphemeVisualizerLazyRouteImport.update({
    id: '/grapheme-visualizer',
    path: '/grapheme-visualizer',
    getParentRoute: () => VVersionRouteRoute,
  } as any).lazy(() =>
    import('./routes/v/$version/grapheme-visualizer.lazy').then((d) => d.Route),
  )
const VVersionFontGlyphViewLazyRoute =
  VVersionFontGlyphViewLazyRouteImport.update({
    id: '/font-glyph-view',
    path: '/font-glyph-view',
    getParentRoute: () => VVersionRouteRoute,
  } as any).lazy(() =>
    import('./routes/v/$version/font-glyph-view.lazy').then((d) => d.Route),
  )
const VVersionBidiLinebreakLazyRoute =
  VVersionBidiLinebreakLazyRouteImport.update({
    id: '/bidi-linebreak',
    path: '/bidi-linebreak',
    getParentRoute: () => VVersionRouteRoute,
  } as any).lazy(() =>
    import('./routes/v/$version/bidi-linebreak.lazy').then((d) => d.Route),
  )
const FileExplorerVSplatRoute = FileExplorerVSplatRouteImport.update({
  id: '/v/$',
  path: '/v/$',
  getParentRoute: () => FileExplorerRouteRoute,
} as any)
const VVersionBlocksIndexLazyRoute = VVersionBlocksIndexLazyRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => VVersionRouteRoute,
} as any).lazy(() =>
  import('./routes/v/$version/blocks/index.lazy').then((d) => d.Route),
)
const VVersionBlocksIdLazyRoute = VVersionBlocksIdLazyRouteImport.update({
  id: '/blocks/$id',
  path: '/blocks/$id',
  getParentRoute: () => VVersionRouteRoute,
} as any).lazy(() =>
  import('./routes/v/$version/blocks/$id.lazy').then((d) => d.Route),
)
const VVersionUHexRoute = VVersionUHexRouteImport.update({
  id: '/u/$hex',
  path: '/u/$hex',
  getParentRoute: () => VVersionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/codepoint-inspector': typeof CodepointInspectorRoute
  '/search': typeof SearchRoute
  '/v/$version': typeof VVersionRouteRouteWithChildren
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/v/': typeof VIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version/bidi-linebreak': typeof VVersionBidiLinebreakLazyRoute
  '/v/$version/font-glyph-view': typeof VVersionFontGlyphViewLazyRoute
  '/v/$version/grapheme-visualizer': typeof VVersionGraphemeVisualizerLazyRoute
  '/v/$version/normalization-preview': typeof VVersionNormalizationPreviewLazyRoute
  '/v/$version/': typeof VVersionIndexRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdLazyRoute
  '/v/$version/blocks/': typeof VVersionBlocksIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/codepoint-inspector': typeof CodepointInspectorRoute
  '/search': typeof SearchRoute
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/v': typeof VIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version/bidi-linebreak': typeof VVersionBidiLinebreakLazyRoute
  '/v/$version/font-glyph-view': typeof VVersionFontGlyphViewLazyRoute
  '/v/$version/grapheme-visualizer': typeof VVersionGraphemeVisualizerLazyRoute
  '/v/$version/normalization-preview': typeof VVersionNormalizationPreviewLazyRoute
  '/v/$version': typeof VVersionIndexRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdLazyRoute
  '/v/$version/blocks': typeof VVersionBlocksIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-explorer': typeof FileExplorerRouteRouteWithChildren
  '/codepoint-inspector': typeof CodepointInspectorRoute
  '/search': typeof SearchRoute
  '/v/$version': typeof VVersionRouteRouteWithChildren
  '/file-explorer/$': typeof FileExplorerSplatRoute
  '/v/': typeof VIndexRoute
  '/file-explorer/v/$': typeof FileExplorerVSplatRoute
  '/v/$version/bidi-linebreak': typeof VVersionBidiLinebreakLazyRoute
  '/v/$version/font-glyph-view': typeof VVersionFontGlyphViewLazyRoute
  '/v/$version/grapheme-visualizer': typeof VVersionGraphemeVisualizerLazyRoute
  '/v/$version/normalization-preview': typeof VVersionNormalizationPreviewLazyRoute
  '/v/$version/': typeof VVersionIndexRoute
  '/v/$version/u/$hex': typeof VVersionUHexRoute
  '/v/$version/blocks/$id': typeof VVersionBlocksIdLazyRoute
  '/v/$version/blocks/': typeof VVersionBlocksIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-explorer'
    | '/codepoint-inspector'
    | '/search'
    | '/v/$version'
    | '/file-explorer/$'
    | '/v/'
    | '/file-explorer/v/$'
    | '/v/$version/bidi-linebreak'
    | '/v/$version/font-glyph-view'
    | '/v/$version/grapheme-visualizer'
    | '/v/$version/normalization-preview'
    | '/v/$version/'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks/$id'
    | '/v/$version/blocks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-explorer'
    | '/codepoint-inspector'
    | '/search'
    | '/file-explorer/$'
    | '/v'
    | '/file-explorer/v/$'
    | '/v/$version/bidi-linebreak'
    | '/v/$version/font-glyph-view'
    | '/v/$version/grapheme-visualizer'
    | '/v/$version/normalization-preview'
    | '/v/$version'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks/$id'
    | '/v/$version/blocks'
  id:
    | '__root__'
    | '/'
    | '/file-explorer'
    | '/codepoint-inspector'
    | '/search'
    | '/v/$version'
    | '/file-explorer/$'
    | '/v/'
    | '/file-explorer/v/$'
    | '/v/$version/bidi-linebreak'
    | '/v/$version/font-glyph-view'
    | '/v/$version/grapheme-visualizer'
    | '/v/$version/normalization-preview'
    | '/v/$version/'
    | '/v/$version/u/$hex'
    | '/v/$version/blocks/$id'
    | '/v/$version/blocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileExplorerRouteRoute: typeof FileExplorerRouteRouteWithChildren
  CodepointInspectorRoute: typeof CodepointInspectorRoute
  SearchRoute: typeof SearchRoute
  VVersionRouteRoute: typeof VVersionRouteRouteWithChildren
  VIndexRoute: typeof VIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codepoint-inspector': {
      id: '/codepoint-inspector'
      path: '/codepoint-inspector'
      fullPath: '/codepoint-inspector'
      preLoaderRoute: typeof CodepointInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-explorer': {
      id: '/file-explorer'
      path: '/file-explorer'
      fullPath: '/file-explorer'
      preLoaderRoute: typeof FileExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/': {
      id: '/v/'
      path: '/v'
      fullPath: '/v/'
      preLoaderRoute: typeof VIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-explorer/$': {
      id: '/file-explorer/$'
      path: '/$'
      fullPath: '/file-explorer/$'
      preLoaderRoute: typeof FileExplorerSplatRouteImport
      parentRoute: typeof FileExplorerRouteRoute
    }
    '/v/$version': {
      id: '/v/$version'
      path: '/v/$version'
      fullPath: '/v/$version'
      preLoaderRoute: typeof VVersionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$version/': {
      id: '/v/$version/'
      path: '/'
      fullPath: '/v/$version/'
      preLoaderRoute: typeof VVersionIndexRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/normalization-preview': {
      id: '/v/$version/normalization-preview'
      path: '/normalization-preview'
      fullPath: '/v/$version/normalization-preview'
      preLoaderRoute: typeof VVersionNormalizationPreviewLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/grapheme-visualizer': {
      id: '/v/$version/grapheme-visualizer'
      path: '/grapheme-visualizer'
      fullPath: '/v/$version/grapheme-visualizer'
      preLoaderRoute: typeof VVersionGraphemeVisualizerLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/font-glyph-view': {
      id: '/v/$version/font-glyph-view'
      path: '/font-glyph-view'
      fullPath: '/v/$version/font-glyph-view'
      preLoaderRoute: typeof VVersionFontGlyphViewLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/bidi-linebreak': {
      id: '/v/$version/bidi-linebreak'
      path: '/bidi-linebreak'
      fullPath: '/v/$version/bidi-linebreak'
      preLoaderRoute: typeof VVersionBidiLinebreakLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/file-explorer/v/$': {
      id: '/file-explorer/v/$'
      path: '/v/$'
      fullPath: '/file-explorer/v/$'
      preLoaderRoute: typeof FileExplorerVSplatRouteImport
      parentRoute: typeof FileExplorerRouteRoute
    }
    '/v/$version/blocks/': {
      id: '/v/$version/blocks/'
      path: '/blocks'
      fullPath: '/v/$version/blocks/'
      preLoaderRoute: typeof VVersionBlocksIndexLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/blocks/$id': {
      id: '/v/$version/blocks/$id'
      path: '/blocks/$id'
      fullPath: '/v/$version/blocks/$id'
      preLoaderRoute: typeof VVersionBlocksIdLazyRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
    '/v/$version/u/$hex': {
      id: '/v/$version/u/$hex'
      path: '/u/$hex'
      fullPath: '/v/$version/u/$hex'
      preLoaderRoute: typeof VVersionUHexRouteImport
      parentRoute: typeof VVersionRouteRoute
    }
  }
}

interface FileExplorerRouteRouteChildren {
  FileExplorerSplatRoute: typeof FileExplorerSplatRoute
  FileExplorerVSplatRoute: typeof FileExplorerVSplatRoute
}

const FileExplorerRouteRouteChildren: FileExplorerRouteRouteChildren = {
  FileExplorerSplatRoute: FileExplorerSplatRoute,
  FileExplorerVSplatRoute: FileExplorerVSplatRoute,
}

const FileExplorerRouteRouteWithChildren =
  FileExplorerRouteRoute._addFileChildren(FileExplorerRouteRouteChildren)

interface VVersionRouteRouteChildren {
  VVersionBidiLinebreakLazyRoute: typeof VVersionBidiLinebreakLazyRoute
  VVersionFontGlyphViewLazyRoute: typeof VVersionFontGlyphViewLazyRoute
  VVersionGraphemeVisualizerLazyRoute: typeof VVersionGraphemeVisualizerLazyRoute
  VVersionNormalizationPreviewLazyRoute: typeof VVersionNormalizationPreviewLazyRoute
  VVersionIndexRoute: typeof VVersionIndexRoute
  VVersionUHexRoute: typeof VVersionUHexRoute
  VVersionBlocksIdLazyRoute: typeof VVersionBlocksIdLazyRoute
  VVersionBlocksIndexLazyRoute: typeof VVersionBlocksIndexLazyRoute
}

const VVersionRouteRouteChildren: VVersionRouteRouteChildren = {
  VVersionBidiLinebreakLazyRoute: VVersionBidiLinebreakLazyRoute,
  VVersionFontGlyphViewLazyRoute: VVersionFontGlyphViewLazyRoute,
  VVersionGraphemeVisualizerLazyRoute: VVersionGraphemeVisualizerLazyRoute,
  VVersionNormalizationPreviewLazyRoute: VVersionNormalizationPreviewLazyRoute,
  VVersionIndexRoute: VVersionIndexRoute,
  VVersionUHexRoute: VVersionUHexRoute,
  VVersionBlocksIdLazyRoute: VVersionBlocksIdLazyRoute,
  VVersionBlocksIndexLazyRoute: VVersionBlocksIndexLazyRoute,
}

const VVersionRouteRouteWithChildren = VVersionRouteRoute._addFileChildren(
  VVersionRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileExplorerRouteRoute: FileExplorerRouteRouteWithChildren,
  CodepointInspectorRoute: CodepointInspectorRoute,
  SearchRoute: SearchRoute,
  VVersionRouteRoute: VVersionRouteRouteWithChildren,
  VIndexRoute: VIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
