import { RouteDependenciesSection } from "#components/inspect/route-dependencies-section";
import { RouteFlowSection } from "#components/inspect/route-flow-section";
import { RouteOutputsSection } from "#components/inspect/route-outputs-section";
import { RouteTransformsSection } from "#components/inspect/route-transforms-section";
import { useInspectData } from "#hooks/use-inspect-data";
import { createFileRoute, getRouteApi } from "@tanstack/react-router";
import { Badge } from "@ucdjs-internal/shared-ui/ui/badge";
import { Button } from "@ucdjs-internal/shared-ui/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@ucdjs-internal/shared-ui/ui/card";
import { Input } from "@ucdjs-internal/shared-ui/ui/input";
import { ArrowRight, FileOutput, FolderOutput, Link2, Workflow as PipelineIcon, Shuffle, Spline } from "lucide-react";
import { useMemo } from "react";

const PipelineRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId");

export const Route = createFileRoute("/s/$sourceId/$sourceFileId/$pipelineId/inspect")({
  validateSearch: (search): {
    q?: string;
    route?: string;
    transform?: string;
    output?: string;
  } => ({
    q: typeof search.q === "string" ? search.q : undefined,
    route: typeof search.route === "string" ? search.route : undefined,
    transform: typeof search.transform === "string" ? search.transform : undefined,
    output: typeof search.output === "string" ? search.output : undefined,
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const { pipelineResponse } = PipelineRoute.useLoaderData();
  const pipeline = pipelineResponse.pipeline;
  const {
    search,
    selectedRoute,
    setSearchQuery,
    navigateToRoute,
    navigateToTransform,
    navigateToOutput,
    clearRouteFocus,
    clearTransformFocus,
    clearOutputFocus,
  } = useInspectData();

  const filteredRoutes = useMemo(() => {
    const value = search.q?.trim().toLowerCase() ?? "";
    if (!value) {
      return pipeline.routes;
    }

    return pipeline.routes.filter((route) => {
      if (route.id.toLowerCase().includes(value)) {
        return true;
      }

      if (route.transforms.some((transform) => transform.toLowerCase().includes(value))) {
        return true;
      }

      if (route.outputs.some((output) => {
        return (output.dir ?? "Default route output directory").toLowerCase().includes(value)
          || (output.fileName ?? "Generated by route configuration").toLowerCase().includes(value);
      })) {
        return true;
      }

      return route.emits.some((emit) => emit.id.toLowerCase().includes(value))
        || route.depends.some((dependency) => (
          dependency.type === "route"
            ? dependency.routeId.toLowerCase().includes(value)
            : `${dependency.routeId}:${dependency.artifactName}`.toLowerCase().includes(value)
        ));
    });
  }, [pipeline.routes, search.q]);

  const transformCount = useMemo(() => {
    return new Set(pipeline.routes.flatMap((route) => route.transforms)).size;
  }, [pipeline.routes]);

  const outputCount = useMemo(() => {
    return pipeline.routes.reduce((count, route) => count + route.outputs.length, 0);
  }, [pipeline.routes]);

  const transforms = useMemo(() => {
    const transformMap = new Map<string, string[]>();

    for (const route of pipeline.routes) {
      for (const transform of route.transforms) {
        const routes = transformMap.get(transform);
        if (routes) {
          routes.push(route.id);
        } else {
          transformMap.set(transform, [route.id]);
        }
      }
    }

    return Array.from(transformMap.entries(), ([name, routes]) => ({ name, routes }))
      .sort((left, right) => left.name.localeCompare(right.name));
  }, [pipeline.routes]);

  const outputs = useMemo(() => {
    return pipeline.routes.flatMap((route) => {
      return route.outputs.map((output, index) => ({
        key: `${route.id}:${index}`,
        routeId: route.id,
        outputIndex: index,
        dir: output.dir ?? "Default route output directory",
        fileName: output.fileName ?? "Generated by route configuration",
      }));
    });
  }, [pipeline.routes]);

  const selectedTransform = search.transform
    ? transforms.find((transform) => transform.name === search.transform) ?? null
    : null;

  const selectedOutput = search.output
    ? outputs.find((output) => output.key === search.output) ?? null
    : null;

  const routeOutputs = selectedOutput
    ? outputs.filter((output) => output.routeId === selectedOutput.routeId)
    : [];

  return (
    <div className="p-4 sm:p-6">
      <div className="grid gap-6 xl:grid-cols-[22rem_minmax(0,1fr)]">
        <aside className="space-y-4 xl:sticky xl:top-6 xl:self-start">
          <Card>
            <CardHeader className="border-b border-border/60 pb-4">
              <div className="flex items-start gap-3">
                <div className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-muted/10">
                  <PipelineIcon className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="space-y-1">
                  <div className="text-[11px] font-medium uppercase tracking-[0.16em] text-muted-foreground">Inspect</div>
                  <CardTitle className="text-base">Routes</CardTitle>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4 pt-5">
              <div className="flex flex-wrap gap-4 text-xs text-muted-foreground">
                <span className="inline-flex items-center gap-1.5">
                  <Spline className="h-3.5 w-3.5" />
                  <span className="font-medium tabular-nums text-foreground">{pipeline.routes.length}</span>
                </span>
                <span className="inline-flex items-center gap-1.5">
                  <Shuffle className="h-3.5 w-3.5" />
                  <span className="font-medium tabular-nums text-foreground">{transformCount}</span>
                </span>
                <span className="inline-flex items-center gap-1.5">
                  <FolderOutput className="h-3.5 w-3.5" />
                  <span className="font-medium tabular-nums text-foreground">{outputCount}</span>
                </span>
              </div>

              <div className="space-y-3">
                <div className="flex items-center justify-between gap-2">
                  <div className="text-xs text-muted-foreground">
                    {filteredRoutes.length}
                    {" "}
                    shown
                  </div>
                  {selectedRoute && (
                    <Button type="button" variant="ghost" size="sm" onClick={clearRouteFocus}>
                      Clear
                    </Button>
                  )}
                </div>

                <Input
                  value={search.q ?? ""}
                  onChange={(event) => {
                    setSearchQuery(event.target.value || undefined);
                  }}
                  placeholder="Search routes, transforms, outputs, dependencies"
                  aria-label="Search inspect routes"
                />
              </div>

              <div className="rounded-xl border border-border/60">
                {filteredRoutes.length === 0
                  ? (
                      <div className="px-4 py-10 text-sm text-muted-foreground">
                        No routes match the current filter.
                      </div>
                    )
                  : (
                      <div className="divide-y divide-border/60">
                        {filteredRoutes.map((route) => {
                          const isActiveRoute = route.id === selectedRoute?.id;

                          return (
                            <button
                              key={route.id}
                              type="button"
                              onClick={() => navigateToRoute(route.id)}
                              className={`relative flex w-full flex-col gap-2 px-4 py-3 text-left transition-colors ${isActiveRoute ? "bg-muted/20" : "hover:bg-muted/10"}`}
                            >
                              {isActiveRoute && <span className="absolute inset-y-2 left-0 w-0.5 rounded-full bg-foreground/80" />}
                              <div className="flex items-center justify-between gap-3">
                                <div className="min-w-0">
                                  <div className="truncate text-sm font-medium text-foreground">{route.id}</div>
                                </div>
                                {route.cache && <Badge variant="secondary" className="text-[10px]">Cacheable</Badge>}
                              </div>
                              <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-muted-foreground">
                                <span>{route.depends.length} depends</span>
                                <span>{route.transforms.length} transforms</span>
                                <span>{route.outputs.length} outputs</span>
                              </div>
                            </button>
                          );
                        })}
                      </div>
                    )}
              </div>
            </CardContent>
          </Card>
        </aside>

        <main className="min-w-0 space-y-4">
          {!selectedRoute && (
            <Card className="flex min-h-[28rem] items-center justify-center">
              <CardContent className="flex w-full items-center justify-center p-6">
                <div className="max-w-md space-y-4 text-center">
                  <div className="mx-auto flex size-14 items-center justify-center rounded-2xl border border-border bg-muted/20">
                    <Spline className="h-6 w-6 text-muted-foreground" />
                  </div>
                  <div className="space-y-2">
                    <h2 className="text-xl font-semibold tracking-tight">Pick a route to start inspecting</h2>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {selectedRoute && (
            <>
              {(selectedTransform || selectedOutput) && (
                <Card>
                  <CardContent className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm">
                    <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-muted-foreground">
                      {selectedTransform && (
                        <span>
                          Transform:
                          {" "}
                          <span className="font-medium text-foreground">{selectedTransform.name}</span>
                        </span>
                      )}
                      {selectedOutput && (
                        <span>
                          Output:
                          {" "}
                          <span className="font-medium text-foreground">
                            {selectedOutput.routeId}
                            {" "}
                            output
                            {selectedOutput.outputIndex + 1}
                          </span>
                        </span>
                      )}
                    </div>
                    <div className="flex gap-2">
                      {selectedTransform && (
                        <Button type="button" variant="ghost" size="sm" onClick={clearTransformFocus}>
                          Clear transform
                        </Button>
                      )}
                      {selectedOutput && (
                        <Button type="button" variant="ghost" size="sm" onClick={clearOutputFocus}>
                          Clear output
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              )}

              <Card>
                <CardContent className="space-y-5 pt-5">
                  <div className="flex flex-wrap items-start justify-between gap-5">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <div className="flex size-10 items-center justify-center rounded-2xl bg-muted/10">
                          <Spline className="h-4 w-4 text-muted-foreground" />
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <h2 className="text-xl font-semibold tracking-tight">{selectedRoute.id}</h2>
                            {selectedRoute.cache
                              ? <Badge variant="secondary">Cacheable</Badge>
                              : null}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div>
                      <div className="grid min-w-[15rem] grid-cols-3 gap-4">
                        <div className="space-y-1">
                          <Link2 className="h-3.5 w-3.5 text-muted-foreground" />
                          <div className="text-sm font-semibold tabular-nums text-foreground">{selectedRoute.depends.length}</div>
                          <div className="text-[11px] text-muted-foreground">depends</div>
                        </div>
                        <div className="space-y-1">
                          <Shuffle className="h-3.5 w-3.5 text-muted-foreground" />
                          <div className="text-sm font-semibold tabular-nums text-foreground">{selectedRoute.transforms.length}</div>
                          <div className="text-[11px] text-muted-foreground">transforms</div>
                        </div>
                        <div className="space-y-1">
                          <FolderOutput className="h-3.5 w-3.5 text-muted-foreground" />
                          <div className="text-sm font-semibold tabular-nums text-foreground">{selectedRoute.outputs.length}</div>
                          <div className="text-[11px] text-muted-foreground">outputs</div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="grid gap-4 border-t border-border/60 pt-4 lg:grid-cols-2">
                    <div className="space-y-2">
                      <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Route filter</div>
                      <code className="block break-all rounded-lg border border-border/60 px-3 py-3 text-xs">
                        {selectedRoute.filter ?? "Custom filter"}
                      </code>
                    </div>
                    {pipeline.include && (
                      <div className="space-y-2">
                        <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Pipeline scope</div>
                        <code className="block break-all rounded-lg border border-border/60 px-3 py-3 text-xs">
                          {pipeline.include}
                        </code>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {selectedTransform && (
                <Card>
                  <CardContent className="space-y-4 pt-5">
                    <div className="flex flex-wrap items-start justify-between gap-4">
                      <div className="space-y-2">
                        <div className="flex items-center gap-2">
                          <div className="flex size-10 items-center justify-center rounded-2xl bg-muted/10">
                            <Shuffle className="h-4 w-4 text-muted-foreground" />
                          </div>
                          <div>
                            <div className="flex items-center gap-2">
                              <h3 className="text-lg font-semibold tracking-tight">{selectedTransform.name}</h3>
                              <Badge variant="secondary">
                                {selectedTransform.routes.length}
                                {" "}
                                {selectedTransform.routes.length === 1 ? "route" : "routes"}
                              </Badge>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="grid gap-3 md:grid-cols-2">
                      {selectedTransform.routes.map((routeId) => (
                        <div key={routeId} className="rounded-xl border border-border/60 p-4">
                          <div className="flex items-start justify-between gap-3">
                            <div>
                              <div className="text-sm font-medium">{routeId}</div>
                            </div>
                            <div className="flex gap-2">
                              <Button
                                type="button"
                                size="sm"
                                variant="outline"
                                onClick={() => navigateToTransform(selectedTransform.name, routeId)}
                              >
                                Focus here
                              </Button>
                              <Button
                                type="button"
                                size="sm"
                                variant="ghost"
                                onClick={() => navigateToRoute(routeId)}
                              >
                                Route
                                <ArrowRight className="h-3 w-3" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}

              {selectedOutput && (
                <Card>
                  <CardContent className="space-y-4 pt-5">
                    <div className="flex flex-wrap items-start justify-between gap-4">
                      <div className="space-y-2">
                        <div className="flex items-center gap-2">
                          <div className="flex size-10 items-center justify-center rounded-2xl bg-muted/10">
                            <FolderOutput className="h-4 w-4 text-muted-foreground" />
                          </div>
                          <div>
                            <div className="flex items-center gap-2">
                              <h3 className="text-lg font-semibold tracking-tight">
                                {selectedOutput.routeId}
                                {" "}
                                output
                                {selectedOutput.outputIndex + 1}
                              </h3>
                              <Badge variant="secondary">
                                {routeOutputs.length}
                                {" "}
                                {routeOutputs.length === 1 ? "route output" : "route outputs"}
                              </Badge>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="grid gap-4 lg:grid-cols-2">
                      <div className="space-y-2">
                        <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Directory</div>
                        <code className="block rounded-lg border border-border/60 px-3 py-3 text-xs">
                          {selectedOutput.dir}
                        </code>
                      </div>
                      <div className="space-y-2">
                        <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">File name</div>
                        <code className="block rounded-lg border border-border/60 px-3 py-3 text-xs">
                          {selectedOutput.fileName}
                        </code>
                      </div>
                    </div>

                    <div className="space-y-3">
                      <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Other outputs on this route</div>
                      <div className="grid gap-3 md:grid-cols-2">
                        {routeOutputs.map((output) => {
                          const active = output.key === selectedOutput.key;
                          return (
                            <Button
                              key={output.key}
                              type="button"
                              variant={active ? "secondary" : "outline"}
                              onClick={() => navigateToOutput(output.routeId, output.outputIndex)}
                              className={`h-auto justify-start rounded-xl px-4 py-4 text-left ${active ? "border-border bg-muted/20" : ""}`}
                            >
                              <div className="w-full">
                                <div className="flex items-center gap-2 text-sm font-medium">
                                  <FileOutput className="h-3.5 w-3.5" />
                                  Output
                                  {" "}
                                  {output.outputIndex + 1}
                                </div>
                                <div className="mt-2 text-xs text-muted-foreground">{output.fileName}</div>
                                <div className="mt-1 text-xs text-muted-foreground">{output.dir}</div>
                              </div>
                            </Button>
                          );
                        })}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}

              <div className="grid gap-4 xl:grid-cols-2">
                <RouteFlowSection />
                <RouteDependenciesSection />
                <RouteTransformsSection />
                <RouteOutputsSection />
              </div>
            </>
          )}
        </main>
      </div>
    </div>
  );
}
