name: 🐛 Bug Report
description: Report an issue that should be fixed
labels: [triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. It helps make UCDJS better.

        If you need help or support using UCDJS, and are not reporting a bug, please ask questions in [GitHub Discussions](https://github.com/orgs/ucdjs/discussions).

        Please try to include as much information as possible.
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: What do you see instead?
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
