import type { BundleableFile } from "./types";
import { flattenVersion } from "./utils";

export interface BundleOptions {
  /**
   * The processed files to bundle, all belonging to the same version.
   */
  results: BundleableFile[];

  /**
   * The full Unicode version string (e.g. "17.0.0").
   */
  version: string;
}

export function bundleCodegen({ results, version }: BundleOptions): string {
  const generatedAt = new Date().toISOString();
  const fileCount = results.length;

  let code = `// This file is generated by ucd codegen. Do not edit this file directly.\n`;
  code += `// Unicode Version: ${flattenVersion(version)}\n`;
  code += `// Generated At: ${generatedAt}\n`;
  code += `// Files: ${fileCount}\n`;
  for (const result of results) {
    code += `//   - ${result.filePath}\n`;
  }

  for (const result of results) {
    code += `\n// #region ${result.filePath}\n`;
    code += result.code;
    code += `\n// #endregion\n`;
  }

  return code;
}
