import type { LanguageModel } from "ai";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { sanitizeIdentifier, toPascalCase, toSnakeCase } from "@luxass/utils";
import { createConcurrencyLimiter } from "@ucdjs-internal/shared";
import { RawDataFile } from "@unicode-utils/core";
import { generateFields } from "./fields";

const TXT_EXTENSION_RE = /\.txt$/;

export interface CodegenFile {
  /**
   * The filePath to the data file.
   */
  filePath: string;

  /**
   * The version of the data file.
   */
  version: string;
}

export interface ProcessedFile {
  fields: {
    type: string;
    name: string;
    description: string;
  }[];
  code: string;
  fileName: string;
  version: string;
}

export interface CodegenOptions {
  /**
   * Files to generate structures for.
   */
  files: CodegenFile[];

  /**
   * The OpenAI API key to use for generating the fields.
   */
  openaiKey?: string;

  /**
   * The OpenAI model to use for generating fields.
   * NOTE:
   * This is good for testing purposes, where you
   * can provide a mock model to test the generation.
   *
   * If not provided, it will create a new OpenAI instance
   * with the default model.
   *
   * SEE: https://ai-sdk.dev/docs/ai-sdk-core/testing
   */
  model?: LanguageModel;
}

function buildInterface(name: string, fields: Record<string, string>, opts?: { export?: boolean }): string {
  const prefix = opts?.export ? "export " : "";
  const body = Object.entries(fields)
    .map(([key, type]) => `  ${key}: ${type};`)
    .join("\n");
  return `${prefix}interface ${name} {\n${body}\n}`;
}

function buildStringArray(values: string[]): string {
  return `[${values.map((v) => `"${v}"`).join(", ")}]`;
}

export async function runCodegen(options: CodegenOptions): Promise<ProcessedFile[]> {
  const inputFiles = options.files;

  const limit = createConcurrencyLimiter(10);

  if (!options.openaiKey && !options.model) {
    throw new Error("Either openaiKey or model must be provided");
  }

  const processPromises = inputFiles.map(({ filePath, version }) =>
    limit(() => processFile({
      filePath,
      openaiKey: options.openaiKey,
      version,
      model: options.model,
    })),
  );

  return Promise.all(processPromises)
    .then((results) => results.filter((result: ProcessedFile | null): result is ProcessedFile => result !== null));
}

interface ProcessFileRequest {
  filePath: string;
  openaiKey?: string;
  version: string;
  model?: LanguageModel;
}

async function processFile(request: ProcessFileRequest): Promise<ProcessedFile | null> {
  const {
    filePath,
    openaiKey,
    version,
    model,
  } = request;
  try {
    // eslint-disable-next-line no-console
    console.log(`Processing file: ${filePath}`);
    const content = await readFile(filePath, "utf-8");
    const fileName = path.basename(filePath).replace(TXT_EXTENSION_RE, "");
    const datafile = new RawDataFile(content);

    const fields = await generateFields({
      datafile,
      apiKey: openaiKey,
      model,
    });

    if (fields == null) {
      console.error(`Error generating fields for file: ${filePath}`);
      return null;
    }

    let code = ``;

    const properties: Record<string, string> = {};

    for (const field of fields) {
      if (properties[field.name] != null) {
        console.error(`Duplicate field name ${field.name} in file ${filePath}. Skipping field.`);
        continue;
      }
      properties[field.name] = field.type;
    }

    code += `// This file is generated by ucd codegen. Do not edit this file directly.\n`;
    code += `// Unicode Version: ${version}\n\n`;
    code += `${buildInterface(sanitizeIdentifier(toPascalCase(fileName)), properties, {
      export: true,
    })}\n\n`;
    code += `export const ${sanitizeIdentifier(
      toSnakeCase(fileName),
    ).toUpperCase()}_FIELDS = ${buildStringArray(fields.map((f) => f.name))};\n`;

    return {
      fields,
      fileName,
      version,
      code,
    };
  } catch (err) {
    console.error(`Error processing file ${filePath}:`, err);
    return null;
  }
}
