import type { PipelineDetails } from "#shared/schemas/pipeline";

export const SIDEBAR_ACTIVE_LINK_CLASS = "relative transition-colors hover:bg-muted/10 [&.active]:bg-muted/10 [&.active]:before:absolute [&.active]:before:inset-y-2 [&.active]:before:left-0 [&.active]:before:w-0.5 [&.active]:before:rounded-full [&.active]:before:bg-foreground/80";

export function deriveTransforms(routes: PipelineDetails["routes"]) {
  const map = new Map<string, string[]>();
  for (const route of routes) {
    for (const transform of route.transforms) {
      const existing = map.get(transform);
      if (existing) {
        existing.push(route.id);
      } else {
        map.set(transform, [route.id]);
      }
    }
  }
  return Array.from(map.entries(), ([name, routeIds]) => ({ name, routes: routeIds }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function deriveOutputs(routes: PipelineDetails["routes"]) {
  return routes.flatMap((route) =>
    route.outputs.map((output, index) => ({
      key: `${route.id}:${index}`,
      routeId: route.id,
      outputIndex: index,
      dir: output.dir ?? "Default route output directory",
      fileName: output.fileName ?? "Generated by route configuration",
    })),
  );
}
