import type { RawDataFile } from "@unicode-utils/core";
import type { LanguageModel } from "ai";
import type { CodegenFile } from "../process";
import { createOpenAI } from "@ai-sdk/openai";
import { sanitizeIdentifier, toPascalCase, toSnakeCase } from "@luxass/utils";
import { createConcurrencyLimiter } from "@ucdjs-internal/shared";
import { buildInterface, buildStringArray } from "../knitwork";
import { processFile } from "../process";
import { generateFields } from "./generate";

export type { GenerateFieldsOptions } from "./generate";
export { generateFields } from "./generate";

export interface ProcessedFieldsFile {
  fields: {
    type: string;
    name: string;
    description: string;
  }[];
  code: string;
  fileName: string;
  version: string;
}

export interface FieldsCodegenOptions {
  /**
   * Files to generate field definitions for.
   */
  files: CodegenFile[];

  /**
   * OpenAI API key. Required when no custom `model` is provided.
   */
  openaiKey?: string;

  /**
   * OpenAI model ID to use when `openaiKey` is provided.
   * @default "gpt-4o-mini"
   */
  modelId?: string;

  /**
   * A custom language model. Useful for testing or non-OpenAI providers.
   * When provided, `openaiKey` and `modelId` are ignored.
   *
   * @see https://ai-sdk.dev/docs/ai-sdk-core/testing
   */
  model?: LanguageModel;
}

async function generateFieldsCode(
  datafile: RawDataFile,
  fileName: string,
  version: string,
  model: LanguageModel,
): Promise<ProcessedFieldsFile | null> {
  const fields = await generateFields({ datafile, model });

  if (fields == null) {
    console.error(`Error generating fields for file: ${fileName}`);
    return null;
  }

  const properties: Record<string, string> = {};
  for (const field of fields) {
    if (properties[field.name] != null) {
      console.error(`Duplicate field name ${field.name} in file ${fileName}. Skipping field.`);
      continue;
    }
    properties[field.name] = field.type;
  }

  let code = `// This file is generated by ucd codegen. Do not edit this file directly.\n`;
  code += `// Unicode Version: ${version}\n\n`;
  code += `${buildInterface(sanitizeIdentifier(toPascalCase(fileName)), properties, { export: true })}\n\n`;
  code += `export const ${sanitizeIdentifier(toSnakeCase(fileName)).toUpperCase()}_FIELDS = ${buildStringArray(Object.keys(properties))};\n`;

  return { fields, fileName, version, code };
}

export async function runFieldsCodegen(options: FieldsCodegenOptions): Promise<ProcessedFieldsFile[]> {
  if (!options.openaiKey && !options.model) {
    throw new Error("Either openaiKey or model must be provided");
  }

  const model = options.model ?? createOpenAI({ apiKey: options.openaiKey })(options.modelId ?? "gpt-4o-mini");
  const limit = createConcurrencyLimiter(10);

  const processPromises = options.files.map(({ filePath, version }) =>
    limit(() => processFile(filePath, version, (datafile, fileName, ver) =>
      generateFieldsCode(datafile, fileName, ver, model))),
  );

  return Promise.all(processPromises)
    .then((results) => results.filter((r): r is ProcessedFieldsFile => r !== null));
}
