import type { LanguageModel } from "ai";
import type { BundleableFile, CodegenFile } from "../types";
import path from "node:path";
import { createOpenAI } from "@ai-sdk/openai";
import { sanitizeIdentifier, toPascalCase, toSnakeCase } from "@luxass/utils";
import { createConcurrencyLimiter, createDebugger } from "@ucdjs-internal/shared";
import { RawDataFile } from "@unicode-utils/core";
import { buildInterface, buildStringArray } from "../knitwork";
import { flattenVersion } from "../utils";
import { generateFields } from "./generate";

const debug = createDebugger("ucdjs:codegen:fields:run");

export type { GenerateFieldsOptions } from "./generate";
export { generateFields } from "./generate";

export interface ProcessedFieldsFile extends BundleableFile {
  fields: {
    type: string;
    name: string;
    description: string;
  }[];
}

export interface FieldsCodegenOptions {
  /**
   * Files to generate field definitions for.
   */
  files: CodegenFile[];

  /**
   * OpenAI API key. Required when no custom `model` is provided.
   */
  openaiKey?: string;

  /**
   * OpenAI model ID to use when `openaiKey` is provided.
   * @default "gpt-4o-mini"
   */
  modelId?: string;

  /**
   * A custom language model. Useful for testing or non-OpenAI providers.
   * When provided, `openaiKey` and `modelId` are ignored.
   *
   * @see https://ai-sdk.dev/docs/ai-sdk-core/testing
   */
  model?: LanguageModel;

  /**
   * Maximum number of files to process concurrently.
   * Lower values reduce the chance of hitting rate limits.
   * @default 3
   */
  concurrency?: number;
}

async function generateFieldsCode(
  datafile: RawDataFile,
  version: string,
  model: LanguageModel,
  filePath: string,
): Promise<ProcessedFieldsFile | null> {
  const fileName = path.basename(filePath, ".txt");
  const unicodePath = path.isAbsolute(filePath) ? `ucd/${fileName}.txt` : filePath;
  const normalizedFilePath = !path.isAbsolute(filePath) && filePath.startsWith("ucd/")
    ? filePath.slice(4)
    : filePath;
  const parentDir = path.dirname(normalizedFilePath);
  const displayName = parentDir && parentDir !== "."
    ? `${parentDir.replace(/\//g, "_")}_${fileName}`
    : fileName;
  const shortVersion = flattenVersion(version);

  debug?.("generating fields code", { filePath, version });
  const fields = await generateFields({ datafile, model, fileName });

  if (fields == null) {
    debug?.("field generation returned null", { filePath });
    return null;
  }

  debug?.("building properties map", { filePath, fieldCount: fields.length });
  const properties: Record<string, string> = {};
  const descriptions: Record<string, string> = {};
  for (const field of fields) {
    if (properties[field.name] != null) {
      debug?.("duplicate field name, skipping", { filePath, fieldName: field.name });
      continue;
    }
    properties[field.name] = field.type;
    if (field.description) {
      descriptions[field.name] = field.description;
    }
  }

  const modelId = typeof model === "string" ? model : model.modelId;
  const generatedAt = new Date().toISOString();
  const fieldCount = Object.keys(properties).length;

  let code = `// This file is generated by ucd codegen. Do not edit this file directly.\n`;
  code += `// Unicode Version: ${shortVersion}\n`;
  code += `// Source File: ${normalizedFilePath}\n`;
  code += `// Unicode Source: https://unicode.org/Public/${version}/${unicodePath}\n`;
  code += `// Model: ${modelId}\n`;
  code += `// Generated At: ${generatedAt}\n`;
  code += `// Fields: ${fieldCount}\n`;
  code += `${buildInterface(sanitizeIdentifier(toPascalCase(displayName)), properties, { export: true, descriptions })}\n\n`;
  code += `export const ${sanitizeIdentifier(toSnakeCase(displayName)).toUpperCase()}_FIELDS = ${buildStringArray(Object.keys(properties))};\n`;

  return { fields, filePath: normalizedFilePath, version, code };
}

const DEFAULT_MODEL_STR = "gpt-4o-mini";

export async function runFieldsCodegen(options: FieldsCodegenOptions): Promise<ProcessedFieldsFile[]> {
  if (!options.openaiKey && !options.model) {
    throw new Error("Either openaiKey or model must be provided");
  }

  const modelStr = options.modelId ?? DEFAULT_MODEL_STR;
  const model = options.model ?? createOpenAI({ apiKey: options.openaiKey })(modelStr);
  const limit = createConcurrencyLimiter(options.concurrency ?? 3);

  debug?.("starting fields codegen", { fileCount: options.files.length, modelId: modelStr });

  // DEBUG: remove this filter before shipping
  const files = options.files.filter((f) => {
    const fileName = path.basename(f.filePath);

    const ALLOWED = ["ArabicShaping.txt", "Scripts.txt"];
    return ALLOWED.includes(fileName);
  });

  const processPromises = files.map((file) => {
    debug?.("processing file", { filePath: file.filePath, version: file.version });
    return limit(async () => {
      const datafile = new RawDataFile(file.content);
      return generateFieldsCode(datafile, file.version, model, file.filePath);
    });
  });

  const results = await Promise.all(processPromises);
  const successful = results.filter((r): r is ProcessedFieldsFile => r !== null);
  debug?.("fields codegen complete", { total: results.length, successful: successful.length, failed: results.length - successful.length });
  return successful;
}
