import { release } from "@ucdjs/release-scripts"

const workspaceRoot = new URL("../", import.meta.url);

release({
  repo: "ucdjs/ucd",
  workspaceRoot: workspaceRoot.pathname,
  packages: {
    excludePrivate: true,
    excluded: [
      "vscode-ucd"
    ]
  },
  safeguards: true,
  prompts: {
    packages: process.env.CI == null,
    versions: process.env.CI == null,
  },
  pullRequest: {
    body: `
      This PR was automatically generated by the UCD release scripts.

      The following packages have been prepared for release:

      <? for (const pkg of packages) { ?>
      - **{{pkg.name}}**: {{pkg.currentVersion}} → {{pkg.newVersion}}
      <? } ?>

      Please review the changes and merge when ready.

      > [!NOTE]
      > When this PR is merged, the release process will be triggered automatically, publishing the new package versions to the registry.
    `
  },
  githubToken: process.env.UCDJS_RELEASE_TOKEN!,
})
