import { createReleaseScripts } from "@ucdjs/release-scripts"

const workspaceRoot = new URL("../", import.meta.url)

const releasePullRequestBody = `
  This PR was automatically generated by the UCD release scripts.

  The following packages have been prepared for release:

  <% if (it.packages.length > 0) { %>
  <% it.packages.forEach((pkg) => { %>
  - **<%= pkg.name %>**: <%= pkg.currentVersion %> → <%= pkg.newVersion %> (<%= pkg.bumpType %>)
  <% }) %>
  <% } else { %>
  There are no packages to release.
  <% } %>

  Please review the changes and merge when ready.

  > [!NOTE]
  > When this PR is merged, the release process will be triggered automatically, publishing the new package versions to the registry.
`

const { prepare, verify, publish } = await createReleaseScripts({
  repo: "ucdjs/ucd",
  workspaceRoot: workspaceRoot.pathname,
  packages: {
    excludePrivate: true,
    exclude: ["vscode-ucd"],
  },
  githubToken: process.env.UCDJS_RELEASE_TOKEN!,
  types: {
    feat: { title: '🚀 Features' },
    fix: { title: '🐞 Bug Fixes' },
    perf: { title: '🏎 Performance' },
    docs: { title: '📚 Documentation' },
    style: { title: '🎨 Styles' },
  },
  globalCommitMode: "dependencies",
  pullRequest: {
    body: releasePullRequestBody,
  },
  changelog: {
    enabled: true,
    emojis: true,
  },
})

const command = process.argv[2] ?? ""

switch (command) {
  case "verify":
    await verify()
    break
  case "prepare":
    await prepare()
    break
  case "publish":
    await publish()
    break
  default:
    console.error("Usage: release <prepare|verify|publish>")
    process.exit(1)
}
