import { release } from "./release-scripts-shared"

release({
  globalCommitMode: "dependencies",
  pullRequest: {
    body: `
      This PR was automatically generated by the UCD release scripts.

      The following packages have been prepared for release:

      <% if (it.packages.length > 0) { %>
      <% it.packages.forEach((pkg) => { %>
      - **<%= pkg.name %>**: <%= pkg.currentVersion %> → <%= pkg.newVersion %> (<%= pkg.bumpType %>)
      <% }) %>
      <% } else { %>
      There are no packages to release.
      <% } %>

      Please review the changes and merge when ready.

      > [!NOTE]
      > When this PR is merged, the release process will be triggered automatically, publishing the new package versions to the registry.
    `
  },
  changelog: {
    enabled: true,
  }
})
