import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { dedent } from "@luxass/utils";
import { MockLanguageModelV3 } from "ai/test";
import { describe, expect, it } from "vitest";
import { testdir } from "vitest-testdirs";
import { runFieldsCodegen } from "../../src/fields/run";

const ROOT_UCD_FILES_PATH = fileURLToPath(new URL("../../../../test/ucd-files", import.meta.url));

function createMockModel(fields: { name: string; type: string; description: string }[]) {
  return new MockLanguageModelV3({
    doGenerate: async () => ({
      finishReason: { raw: undefined, unified: "stop" as const },
      usage: {
        inputTokens: { total: 100, noCache: 100, cacheRead: undefined, cacheWrite: undefined },
        outputTokens: { total: 20, text: 20, reasoning: undefined },
      },
      warnings: [],
      content: [{ type: "text" as const, text: JSON.stringify({ fields }) }],
    }),
  });
}

describe("runFieldsCodegen", () => {
  it("should throw when neither openaiKey nor model is provided", async () => {
    await expect(
      runFieldsCodegen({ files: [{ filePath: "some/file.txt", version: "16.0" }] }),
    ).rejects.toThrow("Either openaiKey or model must be provided");
  });

  it("should return an empty array when no files are provided", async () => {
    const results = await runFieldsCodegen({
      files: [],
      model: createMockModel([]),
    });
    expect(results).toEqual([]);
  });

  it("should generate TypeScript code for a UCD file", async () => {
    const arabicShapingContent = await readFile(
      path.join(ROOT_UCD_FILES_PATH, "v16/ArabicShaping.txt"),
      "utf-8",
    );

    const dir = await testdir({ "ArabicShaping.txt": arabicShapingContent });

    const [result] = await runFieldsCodegen({
      files: [{ filePath: path.join(dir, "ArabicShaping.txt"), version: "16.0" }],
      model: createMockModel([
        { name: "code_point", type: "string", description: "The code point in hexadecimal" },
        { name: "name", type: "string", description: "Schematic name for the character" },
        { name: "joining_type", type: "\"R\" | \"L\" | \"D\" | \"C\" | \"U\" | \"T\"", description: "The joining type" },
        { name: "joining_group", type: "string", description: "The joining group" },
      ]),
    });

    expect(result?.fileName).toBe("ArabicShaping");
    expect(result?.version).toBe("16.0");
    expect(result?.fields).toHaveLength(4);

    expect(result?.code).toBe(`${dedent`
      // This file is generated by ucd codegen. Do not edit this file directly.
      // Unicode Version: 16.0

      export interface ArabicShaping {
        code_point: string;
        name: string;
        joining_type: "R" | "L" | "D" | "C" | "U" | "T";
        joining_group: string;
      }

      export const ARABIC_SHAPING_FIELDS = ["code_point", "name", "joining_type", "joining_group"];
    `}\n`);
  });

  it("should skip duplicate field names, keeping the first occurrence", async () => {
    const arabicShapingContent = await readFile(
      path.join(ROOT_UCD_FILES_PATH, "v16/ArabicShaping.txt"),
      "utf-8",
    );

    const dir = await testdir({ "ArabicShaping.txt": arabicShapingContent });

    const [result] = await runFieldsCodegen({
      files: [{ filePath: path.join(dir, "ArabicShaping.txt"), version: "16.0" }],
      model: createMockModel([
        { name: "code_point", type: "string", description: "first" },
        { name: "code_point", type: "number", description: "duplicate — should be ignored" },
      ]),
    });

    expect(result?.code).toBe(`${dedent`
      // This file is generated by ucd codegen. Do not edit this file directly.
      // Unicode Version: 16.0

      export interface ArabicShaping {
        code_point: string;
      }

      export const ARABIC_SHAPING_FIELDS = ["code_point"];
    `}\n`);
  });

  it("should process multiple files independently", async () => {
    const arabicShapingContent = await readFile(
      path.join(ROOT_UCD_FILES_PATH, "v16/ArabicShaping.txt"),
      "utf-8",
    );

    const dir = await testdir({
      "ArabicShaping.txt": arabicShapingContent,
      "Blocks.txt": arabicShapingContent,
    });

    const results = await runFieldsCodegen({
      files: [
        { filePath: path.join(dir, "ArabicShaping.txt"), version: "16.0" },
        { filePath: path.join(dir, "Blocks.txt"), version: "16.0" },
      ],
      model: createMockModel([
        { name: "start_code_point", type: "string", description: "First code point of the block" },
        { name: "block_name", type: "string", description: "Name of the block" },
      ]),
    });

    expect(results).toHaveLength(2);

    const arabicResult = results.find((r) => r.fileName === "ArabicShaping");
    const blocksResult = results.find((r) => r.fileName === "Blocks");

    expect(arabicResult?.code).toBe(`${dedent`
      // This file is generated by ucd codegen. Do not edit this file directly.
      // Unicode Version: 16.0

      export interface ArabicShaping {
        start_code_point: string;
        block_name: string;
      }

      export const ARABIC_SHAPING_FIELDS = ["start_code_point", "block_name"];
    `}\n`);

    expect(blocksResult?.code).toBe(`${dedent`
      // This file is generated by ucd codegen. Do not edit this file directly.
      // Unicode Version: 16.0

      export interface Blocks {
        start_code_point: string;
        block_name: string;
      }

      export const BLOCKS_FIELDS = ["start_code_point", "block_name"];
    `}\n`);
  });
});
