/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIdRouteRouteImport } from './routes/pipelines/$id/route'
import { Route as PipelinesIdIndexRouteImport } from './routes/pipelines/$id/index'
import { Route as PipelinesIdInspectRouteImport } from './routes/pipelines/$id/inspect'
import { Route as PipelinesIdGraphRouteImport } from './routes/pipelines/$id/graph'
import { Route as PipelinesIdCodeRouteImport } from './routes/pipelines/$id/code'
import { Route as PipelinesIdExecutionsIndexRouteImport } from './routes/pipelines/$id/executions/index'
import { Route as PipelinesIdExecutionsExecutionIdRouteImport } from './routes/pipelines/$id/executions/$executionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdRouteRoute = PipelinesIdRouteRouteImport.update({
  id: '/pipelines/$id',
  path: '/pipelines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdIndexRoute = PipelinesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelinesIdRouteRoute,
} as any)
const PipelinesIdInspectRoute = PipelinesIdInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => PipelinesIdRouteRoute,
} as any)
const PipelinesIdGraphRoute = PipelinesIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => PipelinesIdRouteRoute,
} as any)
const PipelinesIdCodeRoute = PipelinesIdCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => PipelinesIdRouteRoute,
} as any)
const PipelinesIdExecutionsIndexRoute =
  PipelinesIdExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => PipelinesIdRouteRoute,
  } as any)
const PipelinesIdExecutionsExecutionIdRoute =
  PipelinesIdExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => PipelinesIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipelines/$id': typeof PipelinesIdRouteRouteWithChildren
  '/pipelines/$id/code': typeof PipelinesIdCodeRoute
  '/pipelines/$id/graph': typeof PipelinesIdGraphRoute
  '/pipelines/$id/inspect': typeof PipelinesIdInspectRoute
  '/pipelines/$id/': typeof PipelinesIdIndexRoute
  '/pipelines/$id/executions/$executionId': typeof PipelinesIdExecutionsExecutionIdRoute
  '/pipelines/$id/executions/': typeof PipelinesIdExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipelines/$id/code': typeof PipelinesIdCodeRoute
  '/pipelines/$id/graph': typeof PipelinesIdGraphRoute
  '/pipelines/$id/inspect': typeof PipelinesIdInspectRoute
  '/pipelines/$id': typeof PipelinesIdIndexRoute
  '/pipelines/$id/executions/$executionId': typeof PipelinesIdExecutionsExecutionIdRoute
  '/pipelines/$id/executions': typeof PipelinesIdExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipelines/$id': typeof PipelinesIdRouteRouteWithChildren
  '/pipelines/$id/code': typeof PipelinesIdCodeRoute
  '/pipelines/$id/graph': typeof PipelinesIdGraphRoute
  '/pipelines/$id/inspect': typeof PipelinesIdInspectRoute
  '/pipelines/$id/': typeof PipelinesIdIndexRoute
  '/pipelines/$id/executions/$executionId': typeof PipelinesIdExecutionsExecutionIdRoute
  '/pipelines/$id/executions/': typeof PipelinesIdExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipelines/$id'
    | '/pipelines/$id/code'
    | '/pipelines/$id/graph'
    | '/pipelines/$id/inspect'
    | '/pipelines/$id/'
    | '/pipelines/$id/executions/$executionId'
    | '/pipelines/$id/executions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pipelines/$id/code'
    | '/pipelines/$id/graph'
    | '/pipelines/$id/inspect'
    | '/pipelines/$id'
    | '/pipelines/$id/executions/$executionId'
    | '/pipelines/$id/executions'
  id:
    | '__root__'
    | '/'
    | '/pipelines/$id'
    | '/pipelines/$id/code'
    | '/pipelines/$id/graph'
    | '/pipelines/$id/inspect'
    | '/pipelines/$id/'
    | '/pipelines/$id/executions/$executionId'
    | '/pipelines/$id/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelinesIdRouteRoute: typeof PipelinesIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id': {
      id: '/pipelines/$id'
      path: '/pipelines/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof PipelinesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id/': {
      id: '/pipelines/$id/'
      path: '/'
      fullPath: '/pipelines/$id/'
      preLoaderRoute: typeof PipelinesIdIndexRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
    '/pipelines/$id/inspect': {
      id: '/pipelines/$id/inspect'
      path: '/inspect'
      fullPath: '/pipelines/$id/inspect'
      preLoaderRoute: typeof PipelinesIdInspectRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
    '/pipelines/$id/graph': {
      id: '/pipelines/$id/graph'
      path: '/graph'
      fullPath: '/pipelines/$id/graph'
      preLoaderRoute: typeof PipelinesIdGraphRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
    '/pipelines/$id/code': {
      id: '/pipelines/$id/code'
      path: '/code'
      fullPath: '/pipelines/$id/code'
      preLoaderRoute: typeof PipelinesIdCodeRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
    '/pipelines/$id/executions/': {
      id: '/pipelines/$id/executions/'
      path: '/executions'
      fullPath: '/pipelines/$id/executions/'
      preLoaderRoute: typeof PipelinesIdExecutionsIndexRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
    '/pipelines/$id/executions/$executionId': {
      id: '/pipelines/$id/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/pipelines/$id/executions/$executionId'
      preLoaderRoute: typeof PipelinesIdExecutionsExecutionIdRouteImport
      parentRoute: typeof PipelinesIdRouteRoute
    }
  }
}

interface PipelinesIdRouteRouteChildren {
  PipelinesIdCodeRoute: typeof PipelinesIdCodeRoute
  PipelinesIdGraphRoute: typeof PipelinesIdGraphRoute
  PipelinesIdInspectRoute: typeof PipelinesIdInspectRoute
  PipelinesIdIndexRoute: typeof PipelinesIdIndexRoute
  PipelinesIdExecutionsExecutionIdRoute: typeof PipelinesIdExecutionsExecutionIdRoute
  PipelinesIdExecutionsIndexRoute: typeof PipelinesIdExecutionsIndexRoute
}

const PipelinesIdRouteRouteChildren: PipelinesIdRouteRouteChildren = {
  PipelinesIdCodeRoute: PipelinesIdCodeRoute,
  PipelinesIdGraphRoute: PipelinesIdGraphRoute,
  PipelinesIdInspectRoute: PipelinesIdInspectRoute,
  PipelinesIdIndexRoute: PipelinesIdIndexRoute,
  PipelinesIdExecutionsExecutionIdRoute: PipelinesIdExecutionsExecutionIdRoute,
  PipelinesIdExecutionsIndexRoute: PipelinesIdExecutionsIndexRoute,
}

const PipelinesIdRouteRouteWithChildren =
  PipelinesIdRouteRoute._addFileChildren(PipelinesIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelinesIdRouteRoute: PipelinesIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
