/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourceIdRouteRouteImport } from './routes/$sourceId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceIdFileIdRouteRouteImport } from './routes/$sourceId/$fileId/route'
import { Route as SourceIdFileIdPipelineIdRouteRouteImport } from './routes/$sourceId/$fileId/$pipelineId/route'
import { Route as SourceIdFileIdPipelineIdIndexRouteImport } from './routes/$sourceId/$fileId/$pipelineId/index'
import { Route as SourceIdFileIdPipelineIdGraphsRouteImport } from './routes/$sourceId/$fileId/$pipelineId/graphs'
import { Route as SourceIdFileIdPipelineIdCodeRouteImport } from './routes/$sourceId/$fileId/$pipelineId/code'
import { Route as SourceIdFileIdPipelineIdExecutionsIndexRouteImport } from './routes/$sourceId/$fileId/$pipelineId/executions/index'
import { Route as SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRouteImport } from './routes/$sourceId/$fileId/$pipelineId/executions/$executionId/index'
import { Route as SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRouteImport } from './routes/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'

const SourceIdIndexLazyRouteImport = createFileRoute('/$sourceId/')()
const SourceIdFileIdIndexLazyRouteImport = createFileRoute(
  '/$sourceId/$fileId/',
)()
const SourceIdFileIdPipelineIdInspectLazyRouteImport = createFileRoute(
  '/$sourceId/$fileId/$pipelineId/inspect',
)()

const SourceIdRouteRoute = SourceIdRouteRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$sourceId/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceIdIndexLazyRoute = SourceIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourceIdRouteRoute,
} as any).lazy(() =>
  import('./routes/$sourceId/index.lazy').then((d) => d.Route),
)
const SourceIdFileIdRouteRoute = SourceIdFileIdRouteRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => SourceIdRouteRoute,
} as any).lazy(() =>
  import('./routes/$sourceId/$fileId/route.lazy').then((d) => d.Route),
)
const SourceIdFileIdIndexLazyRoute = SourceIdFileIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourceIdFileIdRouteRoute,
} as any).lazy(() =>
  import('./routes/$sourceId/$fileId/index.lazy').then((d) => d.Route),
)
const SourceIdFileIdPipelineIdRouteRoute =
  SourceIdFileIdPipelineIdRouteRouteImport.update({
    id: '/$pipelineId',
    path: '/$pipelineId',
    getParentRoute: () => SourceIdFileIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/route.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdIndexRoute =
  SourceIdFileIdPipelineIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdInspectLazyRoute =
  SourceIdFileIdPipelineIdInspectLazyRouteImport.update({
    id: '/inspect',
    path: '/inspect',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/inspect.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdGraphsRoute =
  SourceIdFileIdPipelineIdGraphsRouteImport.update({
    id: '/graphs',
    path: '/graphs',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/graphs.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdCodeRoute =
  SourceIdFileIdPipelineIdCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/code.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdExecutionsIndexRoute =
  SourceIdFileIdPipelineIdExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/executions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute =
  SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRouteImport.update({
    id: '/executions/$executionId/',
    path: '/executions/$executionId/',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/executions/$executionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute =
  SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRouteImport.update({
    id: '/executions/$executionId/graph',
    path: '/executions/$executionId/graph',
    getParentRoute: () => SourceIdFileIdPipelineIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/$sourceId/$fileId/$pipelineId/executions/$executionId/graph.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sourceId': typeof SourceIdRouteRouteWithChildren
  '/$sourceId/$fileId': typeof SourceIdFileIdRouteRouteWithChildren
  '/$sourceId/': typeof SourceIdIndexLazyRoute
  '/$sourceId/$fileId/$pipelineId': typeof SourceIdFileIdPipelineIdRouteRouteWithChildren
  '/$sourceId/$fileId/': typeof SourceIdFileIdIndexLazyRoute
  '/$sourceId/$fileId/$pipelineId/code': typeof SourceIdFileIdPipelineIdCodeRoute
  '/$sourceId/$fileId/$pipelineId/graphs': typeof SourceIdFileIdPipelineIdGraphsRoute
  '/$sourceId/$fileId/$pipelineId/inspect': typeof SourceIdFileIdPipelineIdInspectLazyRoute
  '/$sourceId/$fileId/$pipelineId/': typeof SourceIdFileIdPipelineIdIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions/': typeof SourceIdFileIdPipelineIdExecutionsIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId/': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$sourceId': typeof SourceIdIndexLazyRoute
  '/$sourceId/$fileId': typeof SourceIdFileIdIndexLazyRoute
  '/$sourceId/$fileId/$pipelineId/code': typeof SourceIdFileIdPipelineIdCodeRoute
  '/$sourceId/$fileId/$pipelineId/graphs': typeof SourceIdFileIdPipelineIdGraphsRoute
  '/$sourceId/$fileId/$pipelineId/inspect': typeof SourceIdFileIdPipelineIdInspectLazyRoute
  '/$sourceId/$fileId/$pipelineId': typeof SourceIdFileIdPipelineIdIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions': typeof SourceIdFileIdPipelineIdExecutionsIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$sourceId': typeof SourceIdRouteRouteWithChildren
  '/$sourceId/$fileId': typeof SourceIdFileIdRouteRouteWithChildren
  '/$sourceId/': typeof SourceIdIndexLazyRoute
  '/$sourceId/$fileId/$pipelineId': typeof SourceIdFileIdPipelineIdRouteRouteWithChildren
  '/$sourceId/$fileId/': typeof SourceIdFileIdIndexLazyRoute
  '/$sourceId/$fileId/$pipelineId/code': typeof SourceIdFileIdPipelineIdCodeRoute
  '/$sourceId/$fileId/$pipelineId/graphs': typeof SourceIdFileIdPipelineIdGraphsRoute
  '/$sourceId/$fileId/$pipelineId/inspect': typeof SourceIdFileIdPipelineIdInspectLazyRoute
  '/$sourceId/$fileId/$pipelineId/': typeof SourceIdFileIdPipelineIdIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions/': typeof SourceIdFileIdPipelineIdExecutionsIndexRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute
  '/$sourceId/$fileId/$pipelineId/executions/$executionId/': typeof SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sourceId'
    | '/$sourceId/$fileId'
    | '/$sourceId/'
    | '/$sourceId/$fileId/$pipelineId'
    | '/$sourceId/$fileId/'
    | '/$sourceId/$fileId/$pipelineId/code'
    | '/$sourceId/$fileId/$pipelineId/graphs'
    | '/$sourceId/$fileId/$pipelineId/inspect'
    | '/$sourceId/$fileId/$pipelineId/'
    | '/$sourceId/$fileId/$pipelineId/executions/'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$sourceId'
    | '/$sourceId/$fileId'
    | '/$sourceId/$fileId/$pipelineId/code'
    | '/$sourceId/$fileId/$pipelineId/graphs'
    | '/$sourceId/$fileId/$pipelineId/inspect'
    | '/$sourceId/$fileId/$pipelineId'
    | '/$sourceId/$fileId/$pipelineId/executions'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId'
  id:
    | '__root__'
    | '/'
    | '/$sourceId'
    | '/$sourceId/$fileId'
    | '/$sourceId/'
    | '/$sourceId/$fileId/$pipelineId'
    | '/$sourceId/$fileId/'
    | '/$sourceId/$fileId/$pipelineId/code'
    | '/$sourceId/$fileId/$pipelineId/graphs'
    | '/$sourceId/$fileId/$pipelineId/inspect'
    | '/$sourceId/$fileId/$pipelineId/'
    | '/$sourceId/$fileId/$pipelineId/executions/'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'
    | '/$sourceId/$fileId/$pipelineId/executions/$executionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SourceIdRouteRoute: typeof SourceIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$sourceId': {
      id: '/$sourceId'
      path: '/$sourceId'
      fullPath: '/$sourceId'
      preLoaderRoute: typeof SourceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sourceId/': {
      id: '/$sourceId/'
      path: '/'
      fullPath: '/$sourceId/'
      preLoaderRoute: typeof SourceIdIndexLazyRouteImport
      parentRoute: typeof SourceIdRouteRoute
    }
    '/$sourceId/$fileId': {
      id: '/$sourceId/$fileId'
      path: '/$fileId'
      fullPath: '/$sourceId/$fileId'
      preLoaderRoute: typeof SourceIdFileIdRouteRouteImport
      parentRoute: typeof SourceIdRouteRoute
    }
    '/$sourceId/$fileId/': {
      id: '/$sourceId/$fileId/'
      path: '/'
      fullPath: '/$sourceId/$fileId/'
      preLoaderRoute: typeof SourceIdFileIdIndexLazyRouteImport
      parentRoute: typeof SourceIdFileIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId': {
      id: '/$sourceId/$fileId/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/$sourceId/$fileId/$pipelineId'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdRouteRouteImport
      parentRoute: typeof SourceIdFileIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/': {
      id: '/$sourceId/$fileId/$pipelineId/'
      path: '/'
      fullPath: '/$sourceId/$fileId/$pipelineId/'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdIndexRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/inspect': {
      id: '/$sourceId/$fileId/$pipelineId/inspect'
      path: '/inspect'
      fullPath: '/$sourceId/$fileId/$pipelineId/inspect'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdInspectLazyRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/graphs': {
      id: '/$sourceId/$fileId/$pipelineId/graphs'
      path: '/graphs'
      fullPath: '/$sourceId/$fileId/$pipelineId/graphs'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdGraphsRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/code': {
      id: '/$sourceId/$fileId/$pipelineId/code'
      path: '/code'
      fullPath: '/$sourceId/$fileId/$pipelineId/code'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdCodeRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/executions/': {
      id: '/$sourceId/$fileId/$pipelineId/executions/'
      path: '/executions'
      fullPath: '/$sourceId/$fileId/$pipelineId/executions/'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdExecutionsIndexRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/executions/$executionId/': {
      id: '/$sourceId/$fileId/$pipelineId/executions/$executionId/'
      path: '/executions/$executionId'
      fullPath: '/$sourceId/$fileId/$pipelineId/executions/$executionId/'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
    '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph': {
      id: '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'
      path: '/executions/$executionId/graph'
      fullPath: '/$sourceId/$fileId/$pipelineId/executions/$executionId/graph'
      preLoaderRoute: typeof SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRouteImport
      parentRoute: typeof SourceIdFileIdPipelineIdRouteRoute
    }
  }
}

interface SourceIdFileIdPipelineIdRouteRouteChildren {
  SourceIdFileIdPipelineIdCodeRoute: typeof SourceIdFileIdPipelineIdCodeRoute
  SourceIdFileIdPipelineIdGraphsRoute: typeof SourceIdFileIdPipelineIdGraphsRoute
  SourceIdFileIdPipelineIdInspectLazyRoute: typeof SourceIdFileIdPipelineIdInspectLazyRoute
  SourceIdFileIdPipelineIdIndexRoute: typeof SourceIdFileIdPipelineIdIndexRoute
  SourceIdFileIdPipelineIdExecutionsIndexRoute: typeof SourceIdFileIdPipelineIdExecutionsIndexRoute
  SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute: typeof SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute
  SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute: typeof SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute
}

const SourceIdFileIdPipelineIdRouteRouteChildren: SourceIdFileIdPipelineIdRouteRouteChildren =
  {
    SourceIdFileIdPipelineIdCodeRoute: SourceIdFileIdPipelineIdCodeRoute,
    SourceIdFileIdPipelineIdGraphsRoute: SourceIdFileIdPipelineIdGraphsRoute,
    SourceIdFileIdPipelineIdInspectLazyRoute:
      SourceIdFileIdPipelineIdInspectLazyRoute,
    SourceIdFileIdPipelineIdIndexRoute: SourceIdFileIdPipelineIdIndexRoute,
    SourceIdFileIdPipelineIdExecutionsIndexRoute:
      SourceIdFileIdPipelineIdExecutionsIndexRoute,
    SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute:
      SourceIdFileIdPipelineIdExecutionsExecutionIdGraphRoute,
    SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute:
      SourceIdFileIdPipelineIdExecutionsExecutionIdIndexRoute,
  }

const SourceIdFileIdPipelineIdRouteRouteWithChildren =
  SourceIdFileIdPipelineIdRouteRoute._addFileChildren(
    SourceIdFileIdPipelineIdRouteRouteChildren,
  )

interface SourceIdFileIdRouteRouteChildren {
  SourceIdFileIdPipelineIdRouteRoute: typeof SourceIdFileIdPipelineIdRouteRouteWithChildren
  SourceIdFileIdIndexLazyRoute: typeof SourceIdFileIdIndexLazyRoute
}

const SourceIdFileIdRouteRouteChildren: SourceIdFileIdRouteRouteChildren = {
  SourceIdFileIdPipelineIdRouteRoute:
    SourceIdFileIdPipelineIdRouteRouteWithChildren,
  SourceIdFileIdIndexLazyRoute: SourceIdFileIdIndexLazyRoute,
}

const SourceIdFileIdRouteRouteWithChildren =
  SourceIdFileIdRouteRoute._addFileChildren(SourceIdFileIdRouteRouteChildren)

interface SourceIdRouteRouteChildren {
  SourceIdFileIdRouteRoute: typeof SourceIdFileIdRouteRouteWithChildren
  SourceIdIndexLazyRoute: typeof SourceIdIndexLazyRoute
}

const SourceIdRouteRouteChildren: SourceIdRouteRouteChildren = {
  SourceIdFileIdRouteRoute: SourceIdFileIdRouteRouteWithChildren,
  SourceIdIndexLazyRoute: SourceIdIndexLazyRoute,
}

const SourceIdRouteRouteWithChildren = SourceIdRouteRoute._addFileChildren(
  SourceIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SourceIdRouteRoute: SourceIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
