/**
 * This file is auto-generated by the `generate:components` script.
 * Do not edit this file directly.
 * Run `pnpm generate:components` to regenerate it.
 */

import type { components } from "./.generated/api";

export type ApiError = components["schemas"]["ApiError"];
export type UnicodeVersionList = components["schemas"]["UnicodeVersionList"];
export type UnicodeTreeNode = components["schemas"]["UnicodeTreeNode"];
export type UnicodeTree = components["schemas"]["UnicodeTree"];
export type FileEntryList = components["schemas"]["FileEntryList"];
