/**
 * This file is auto-generated by the `generate:components` script.
 * Do not edit this file directly.
 * Run `pnpm generate:components` to regenerate it.
 */

import type { components } from "./.generated/api";

export type UnicodeVersion = components["schemas"]["UnicodeVersion"];
export type UnicodeVersions = components["schemas"]["UnicodeVersions"];
export type ApiError = components["schemas"]["ApiError"];
export type ProxyDirectoryResponse = components["schemas"]["ProxyDirectoryResponse"];
export type ProxyFileResponse = components["schemas"]["ProxyFileResponse"];
export type ProxyResponse = components["schemas"]["ProxyResponse"];
