import { createFileRoute, getRouteApi, Link } from "@tanstack/react-router";
import { Badge } from "@ucdjs-internal/shared-ui/ui/badge";
import { Card, CardContent } from "@ucdjs-internal/shared-ui/ui/card";
import { ArrowLeft, ArrowRight, FileOutput, FolderOutput } from "lucide-react";
import { useMemo } from "react";

const PipelineRoute = getRouteApi("/s/$sourceId/$sourceFileId/$pipelineId");

export const Route = createFileRoute("/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs/$outputKey/")({
  component: OutputDetailPage,
});

function OutputDetailPage() {
  const { pipelineResponse } = PipelineRoute.useLoaderData();
  const pipeline = pipelineResponse.pipeline;
  const { sourceId, sourceFileId, pipelineId, outputKey } = Route.useParams();

  const allOutputs = useMemo(() => {
    return pipeline.routes.flatMap((route) =>
      route.outputs.map((output, index) => ({
        key: `${route.id}:${index}`,
        routeId: route.id,
        outputIndex: index,
        dir: output.dir ?? "Default route output directory",
        fileName: output.fileName ?? "Generated by route configuration",
      })),
    );
  }, [pipeline.routes]);

  const selectedOutput = allOutputs.find((o) => o.key === outputKey) ?? null;

  if (!selectedOutput) {
    return (
      <div className="space-y-4">
        <Link
          to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs"
          params={{ sourceId, sourceFileId, pipelineId }}
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to outputs
        </Link>
        <div className="rounded-lg border border-border/60 px-4 py-10 text-sm text-muted-foreground">
          Output &ldquo;{outputKey}&rdquo; not found in this pipeline.
        </div>
      </div>
    );
  }

  const routeOutputs = allOutputs.filter((o) => o.routeId === selectedOutput.routeId);

  return (
    <div className="space-y-4">
      <Link
        to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs"
        params={{ sourceId, sourceFileId, pipelineId }}
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to outputs
      </Link>

      <Card>
        <CardContent className="space-y-4 pt-5">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <div className="flex size-10 items-center justify-center rounded-2xl bg-muted/10">
                <FolderOutput className="h-4 w-4 text-muted-foreground" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-lg font-semibold tracking-tight">
                    {selectedOutput.routeId}
                    {" "}
                    output
                    {selectedOutput.outputIndex + 1}
                  </h3>
                  <Badge variant="secondary">
                    {routeOutputs.length}
                    {" "}
                    {routeOutputs.length === 1 ? "route output" : "route outputs"}
                  </Badge>
                </div>
              </div>
            </div>
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <div className="space-y-2">
              <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Directory</div>
              <code className="block rounded-lg border border-border/60 px-3 py-3 text-xs">
                {selectedOutput.dir}
              </code>
            </div>
            <div className="space-y-2">
              <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">File name</div>
              <code className="block rounded-lg border border-border/60 px-3 py-3 text-xs">
                {selectedOutput.fileName}
              </code>
            </div>
          </div>

          <Link
            to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/routes/$routeId"
            params={{ sourceId, sourceFileId, pipelineId, routeId: selectedOutput.routeId }}
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
          >
            Go to route
            <ArrowRight className="h-3 w-3" />
          </Link>

          <div className="space-y-3">
            <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Other outputs on this route</div>
            <div className="grid gap-3 md:grid-cols-2">
              {routeOutputs.map((output) => {
                const active = output.key === selectedOutput.key;
                return (
                  <Link
                    key={output.key}
                    to="/s/$sourceId/$sourceFileId/$pipelineId/inspect/outputs/$outputKey"
                    params={{ sourceId, sourceFileId, pipelineId, outputKey: output.key }}
                    className={`flex h-auto justify-start rounded-xl border px-4 py-4 text-left ${active ? "border-border bg-muted/20" : "border-input hover:bg-accent hover:text-accent-foreground"}`}
                  >
                    <div className="w-full">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <FileOutput className="h-3.5 w-3.5" />
                        Output
                        {" "}
                        {output.outputIndex + 1}
                      </div>
                      <div className="mt-2 text-xs text-muted-foreground">{output.fileName}</div>
                      <div className="mt-1 text-xs text-muted-foreground">{output.dir}</div>
                    </div>
                  </Link>
                );
              })}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
