extends:
  - "@luxass/spectral-ruleset"

overrides:
  - files:
      - .generated/openapi.json#/paths/~1api~1v1~1files~1.ucd-store.json
    rules:
      luxass/no-file-extensions-in-paths: off
      luxass/paths-kebab-case: off

  - files:
      - .generated/openapi.json#/paths/~1.well-known~1ucd-config.json
    rules:
      luxass/no-file-extensions-in-paths: off
      luxass/paths-kebab-case: off
