name: openapi approve breaking changes

on:
  pull_request:
    types: [labeled, unlabeled]

permissions:
  statuses: write
  pull-requests: read

jobs:
  approve-breaking-changes:
    if: ${{ github.repository == 'ucdjs/ucd' && github.event.label.name == 'approve-breaking-openapi' }}
    runs-on: ubuntu-latest
    steps:
      - name: approve openapi breaking changes
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const headSha = context.payload.pull_request.head.sha;

            console.log(`Approving OpenAPI breaking changes for PR #${prNumber}`);

            // Override the status check to success
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: headSha,
              state: 'success',
              target_url: context.payload.pull_request.html_url,
              description: 'Breaking changes approved via label',
              context: 'openapi-schema-check'
            });

            console.log('Status check overridden to success via approve-breaking-openapi label');
