name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"
      - "!apps/docs/**/*.md"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"
      - "!apps/docs/**/*.md"

# automatically cancel older in-progress jobs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
  FORCE_COLOR: true

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  test:
    name: test (${{ matrix.runs.name }})
    runs-on: ${{ matrix.runs.os }}
    strategy:
      fail-fast: false
      matrix:
        runs:
          - name: ubuntu
            os: ubuntu-latest
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
